### ISSUE TITLE
Help with proofreading and adapting the content with social science examples

### ISSUE THREAD

**Issue by maczokni** [datacarpentry/r-socialsci#1]
So myself and @langtonhugh have just completed our data carpentry training instructor 2-day workshop, and in looking to contribute to something for our checkout tasks, we came across this re-writing of the R material for social sciences.

We thought that the best use of our skills would be to contribute to this by helping proof-read, and amend the sessions with social-sciences related examples.  We just wanted to ask if there is any direction on where to focus, or if you had any particular tasks/ requirements in mind? I had a look at the "reading in data" section, and have some ideas in mind, and have spotted some typos, so happy to make some changes there and then submit a pull request, but also open to steer to focus on other elements if that would be more helpful? Let us know!

---

Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  

Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck (k8hertweck@gmail.com).  

---

**Comment by juanfung** [comment]
Hi @maczokni, I've just started as the maintainer for this lesson. Please feel free to submit a PR for any typos you've spotted! If you'd rather just submit an issue, that works too. 

New examples are always welcome, but will require review by two maintainers. Larger changes will involve even more reviewers. That said, please feel free to submit PRs for your ideas!
