### ISSUE TITLE
render exercises as exercises

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/r-socialsci#10]
Some of the exercises (e.g. in [this episode](http://www.datacarpentry.org/spreadsheets-socialsci/02-reformatting/)) are not formatted as exercises. Exercises and their solutions should be marked with specific syntax detailed [here](http://swcarpentry.github.io/lesson-example/04-formatting/index.html).

**Comment by juanfung** [comment]
@ha0ye Just checking in whether I should take on this issue. Let me know!

**Comment by ha0ye** [comment]
Ah, I think I got up through episode-03, and they mostly looked fine. I'm not sure about the later half of the lessons or what all @fmichonneau had managed to merge in for the bug BBQ.

**Comment by juanfung** [comment]
Okay, thanks! I'll pick up from episode 03, then.

**Comment by fmichonneau** [comment]
the lessons have been fully converted to Rmarkdown, and use the correct template syntax now.
