### ISSUE TITLE
Replace gather/spread with pivot functions

### ISSUE THREAD

**Issue by colinquirk** [datacarpentry/r-socialsci#104]
Gather and spread are going to be phased out in favor of the new pivot functions:
https://twitter.com/hadleywickham/status/1108120330365751298
https://tidyr.tidyverse.org/dev/articles/pivot.html

IMO, gather/spread have always left a lot to be desired and the pivot functions seem to be good replacements. They aren't stable yet, but it's worth thinking about as according to Hadley gather and spread won't be promoted anymore once the new functions go live.

**Comment by katrinleinweber** [comment]
They are even being [demoted](https://www.tidyverse.org/lifecycle/#retired) :-/

[![grafik](https://user-images.githubusercontent.com/9948149/66208445-5cafb980-e6b5-11e9-87e1-fd10dd35f4b0.png)](https://github.com/tidyverse/tidyr/blame/492ea30113da6d4b4072e73dd5c70ef2cfd9cbc6/R/gather.R#L4-L8)

This might be awkward in a workshop when instructors show `?gather`.

**Comment by MonkmanMH** [comment]
Hi, I have submitted a pull request re: this issue: 
https://github.com/datacarpentry/r-socialsci/pull/163

**Comment by juanfung** [comment]
Resolved by #163
