### ISSUE TITLE
discuss why these formatting problems are problematic

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/r-socialsci#11]
Episode 2 has this text:

>> The problems that we can see are as follows:
White space to the top and to the left of the data.
There are two header line types with different data items in each
One of the header line has two separate data items

but it doesn't explain why these are problematic. It would be good to have more exposition about why these are problems (ie. what will happen to the user downstream if they have these formatting issues in their data sheets).

**Comment by ha0ye** [comment]
I'll look into this as well.

**Comment by juanfung** [comment]
@ha0ye Good catch!
