### ISSUE TITLE
Subsetting a tibble with `[` always gives a tibble

### ISSUE THREAD

**Issue by cwickham** [datacarpentry/r-socialsci#110]
In the "Indexing and subsetting data frames" section of the "Starting with Data" 
episode, the examples are preceeded by the statement:
>  However, note that different ways of specifying these coordinates lead to results with different classes.

However, since `interviews` is a tibble this isn't true, every example returns a tibble:
``` r
library(tidyverse)
interviews <- read_csv("data/SAFI_clean.csv", na = "NULL")

## first element in the first column of the data frame (as a vector)
interviews[1, 1]
#> # A tibble: 1 x 1
#>   key_ID
#>    <dbl>
#> 1      1
## first element in the 6th column (as a vector)
interviews[1, 6]
#> # A tibble: 1 x 1
#>   respondent_wall_type
#>   <chr>               
#> 1 muddaub
## first column of the data frame (as a vector)
interviews[, 1]
#> # A tibble: 131 x 1
#>    key_ID
#>     <dbl>
#>  1      1
#>  2      1
#>  3      3
#>  4      4
#>  5      5
#>  6      6
#>  7      7
#>  8      8
#>  9      9
#> 10     10
#> # … with 121 more rows
## first column of the data frame (as a data.frame)
interviews[1]
#> # A tibble: 131 x 1
#>    key_ID
#>     <dbl>
#>  1      1
#>  2      1
#>  3      3
#>  4      4
#>  5      5
#>  6      6
#>  7      7
#>  8      8
#>  9      9
#> 10     10
#> # … with 121 more rows
## first three elements in the 7th column (as a vector)
interviews[1:3, 7]
#> # A tibble: 3 x 1
#>   rooms
#>   <dbl>
#> 1     1
#> 2     1
#> 3     1
## the 3rd row of the data frame (as a data.frame)
interviews[3, ]
#> # A tibble: 1 x 14
#>   key_ID village interview_date      no_membrs years_liv respondent_wall…
#>    <dbl> <chr>   <dttm>                  <dbl>     <dbl> <chr>           
#> 1      3 God     2016-11-17 00:00:00        10        15 burntbricks     
#> # … with 8 more variables: rooms <dbl>, memb_assoc <chr>,
#> #   affect_conflicts <chr>, liv_count <dbl>, items_owned <chr>,
#> #   no_meals <dbl>, months_lack_food <chr>, instanceID <chr>
## equivalent to head_interviews <- head(interviews)
head_interviews <- interviews[1:6, ]
```

So, at the very least the code comments on each line are misleading.  The statement and comments could be removed, but it feels like this behaviour needs addressing somewhere.

Should this distinction be explicitly highlighted? E.g. words to the effect of "you'll always get a tibble back when you use `[`  to subset a tibble, but be careful, this isn't true with data frames".  Or, does this tibble/data frame distinction just confuse people?

**Comment by juanfung** [comment]
I was about to open an issue on this! The easiest thing to do is remove "(as a vector)" comments, but agree that it's an issue that needs clarification.

The "tidy" way to subset a tibble as a vector is `interviews %>% pull(7) %>% head(3)` (or you can `splice` before you `pull`, but this seems unnecessarily cumbersome at this stage in the lesson.

**Comment by ha0ye** [comment]
I think clarification is super-important. Learners will go on to use other resources, which may use non-tibble data.frames as examples, which can lead to confusion / errors. (not to mention how usage of `$` and `[` varies, as well!)
