### ISSUE TITLE
exercise has a wording mistake

### ISSUE THREAD

**Issue by evebohnett** [datacarpentry/r-socialsci#117]
Introducing dplyr and tidyr

In one of the exercises it asks for whether each interview respondent was lacking water in that month. However, the dataset has a column for lacking food. So the exercise needs to be updated for lack of food, not water.

**Comment by angela-li** [comment]
Thank you for bringing this to our attention! @juanfung has fixed it (see changes in commit 9c69f1c283aa99eb01a1a129862ec556f5ec2808)
