### ISSUE TITLE
More suggestion than an issue

### ISSUE THREAD

**Issue by jmjamison** [datacarpentry/r-socialsci#119]
This is really small but I think it would be helpful to include the key combination to clear the R-Studio console: Cntl-L

**Comment by pkiraly** [comment]
@jmjamison 

How about this sentence?

> If there are two much information on the console you don't need anymore, you can clear it with <kbd>Ctrl</kbd> + <kbd>L</kbd>.

**Comment by pkiraly** [comment]
I've created a pull request for this ticket: #131

**Comment by angela-li** [comment]
I edited the sentence a bit, but great teamwork in identifying and tackling this issue @jmjamison and @pkiraly! People are always asking this during workshops, so this is good to add.
