### ISSUE TITLE
01-R basics.md editing typos, formatting, style

### ISSUE THREAD

**Issue by nsbowden** [datacarpentry/r-socialsci#12]
Addresses these issues associated with lesson release checklist

**Comment by juanfung** [comment]
Is this resolved by PR https://github.com/datacarpentry/r-socialsci/pull/16?

**Comment by juanfung** [comment]
Sorry @nsbowden forgot to tag you. Just want to make sure that PR#https://github.com/datacarpentry/r-socialsci/pull/16 resolves this issue.

**Comment by fmichonneau** [comment]
yes, things are looking ok now. I'll commit the rendered files soon. Thanks!
