### ISSUE TITLE
non unique keyID in `SAFI_clean.csv`

### ISSUE THREAD

**Issue by cengel** [datacarpentry/r-socialsci#122]
This is not causing any issues with the materials/code, but may lead to questions: the following `keyID`s are used twice in the interview table: 
- 1 (2 is missing) 
- 21

**Comment by angela-li** [comment]
Will resubmit dataset to FigShare and fix links - I also ran into this confusion during a workshop recently!

**Comment by colinquirk** [comment]
Some KeyIDs are also missing, e.g. 183.

**Comment by atheobold** [comment]
@angela-li - did you resubmit the dataset to FigShare and fix the links? Currently, the data in Figshare and this lesson still have the same issues @cengel pointed out. Additionally, the issue that @colinquirk pointed out substantially underrepresents the amount of missing `keyID`s in the dataset, as there are **a lot** of missing `keyID`s. 

Perhaps a broader question for @kelseygonzalez and @juanfung is whether we feel that the large number of missing `keyID`s should be mentioned in the lesson.

**Comment by juanfung** [comment]
I don't see it as a problem, but okay with changing.

**Comment by atheobold** [comment]
@juanfung and @kelseygonzalez - a new issue I noticed when reviewing the changes to the `dplyr` and `tidyr` lesson, I stated that there are not duplicate `keyID`s in the dataset, which is false. These interviews are at the same village on the same date, but they do not have the same `instanceID`. To me, the discussion of wide/long data formats are complicated by there being duplicated `keyID`s, but I am open to other perspectives!

**Comment by juanfung** [comment]
@atheobold I had to refresh myself on the data set. From the [workshop page](https://datacarpentry.org/socialsci-workshop/data/)
key_id | Added to provide a unique Id for each observation. (The InstanceID field does this as well but it is not as convenient to use)
-- | --

Suggests that duplicate `key_ID`s should not exist. I can't find where in episode 03 you say that, but that is a case where we want to be more careful about the `key_ID`s. I was under the assumption that we don't really use them in the lesson.

**Comment by atheobold** [comment]
In episode 03 I added: 

> We also notice that no `key_ID` was surveyed more than once. As seen in the code 
> below, for each interview date in each village no `key_ID`s are the same. Thus, 
> this format is what is called a "long" data format.
> 

The [FigShare link](https://figshare.com/articles/SAFI_Survey_Results/6262019) from the workshop data page says the same thing about `keyID`s being unique. I suppose we could write to the maintainers of the SAFI data, to request additional information about why there are duplicate `keyID`s?

**Comment by juanfung** [comment]
Yeah why not? :)

**Comment by atheobold** [comment]
This issue was discussed in PR #248, and can be marked as resolved for now.
