### ISSUE TITLE
use separate_rows() instead of strsplit()

### ISSUE THREAD

**Issue by cengel** [datacarpentry/r-socialsci#123]
Suggestion: In episode **Introducing `dplyr` and `tidyr`** - subsection **Applying `spread()` to clean our data** use `separate_rows()` instead of `strsplit()` which eliminates the need to introduce `unnest()` and might be preferable for the beginner.

Instead of: 
```
interviews_items_owned <- interviews %>%
        mutate(split_items = strsplit(items_owned, ";")) %>%
        unnest() %>%
        mutate(items_owned_logical = TRUE) %>%
        spread(key = split_items, value = items_owned_logical, fill = FALSE)
```
Use this:
```
interviews_items_owned <- interviews %>%
        separate_rows(items_owned, sep=";") %>%
        mutate(items_owned_logical = TRUE) %>%
        spread(key = split_items, value = items_owned_logical, fill = FALSE)
```

**Comment by angela-li** [comment]
This is a good point - `separate_rows()` is both more concise and easier for a learner to grasp than `unnest()`. I think is also a better workflow than `mutate() %>% unnest()` in general.

**Comment by angela-li** [comment]
I made an update with the change (note: the `key` in `spread()` also needed to be changed). Will have @juanfung review and merge if it looks good!
