### ISSUE TITLE
Capitalization of lesson episodes needs to be fixed

### ISSUE THREAD

**Issue by pkiraly** [datacarpentry/r-socialsci#129]
The lettercase in the titles of the episodes are not fully synchronized:

- Before we Start
- Starting with Data
- Data visualisation with ggplot2

Either we should change visualisation to Visualisation or Start to start and Data to data. For me the small case seems better. This pull request is only about the first uppercase->smallcase transformation.

**Comment by angela-li** [comment]
Great point! Check out the Carpentries Style Guide for reference: https://docs.carpentries.org/topic_folders/communications/resources/style-guide.html#c. Looks like we want all lesson titles and episode names to be capitalized (and use British English, so *capitalised). I think this would make a good first PR, so leaving it open for now...
