### ISSUE TITLE
631 in long format rather than 131

### ISSUE THREAD

**Issue by symulation** [datacarpentry/r-socialsci#132]
"In this long format version, there are 131 rows (one row for each unique item for each respondent)."

Should say

"In this long format version, there are 631 rows (one row for each unique item for each respondent)."

**Comment by angela-li** [comment]
Thanks! Do you feel able to submit a PR regarding this? If not, I can go ahead and troubleshoot this.

**Comment by juanfung** [comment]
Resolved in #163
