### ISSUE TITLE
Provide intermediate dataset interviews_plotting for learners

### ISSUE THREAD

**Issue by angela-li** [datacarpentry/r-socialsci#133]
As the lesson stands, you can only do the ggplot2 section if you have a tidied version of the dataset (ie. complete the tidyr section before). Occasionally learners fall behind and are unable to tidy everything before moving on to the next section, then are not set up for the ggplot2 part.

I propose providing a link for learners to download the intermediate data if they get lost in the tidyr part, possibly in Instructor Notes or the lesson overview.

**Comment by juanfung** [comment]
This is a great idea @angela-li !

**Comment by juanfung** [comment]
Rather than having to download another data set, maybe we replace
```
interviews_plotting <- read_csv("data_output/interviews_plotting.csv")
```
with the code to create `interviews_plotting`

**Comment by kelseygonzalez** [comment]
@atheobold @juanfung and I decided to include the code to create `interviews_plotting` at the beginning of the lesson for those who may not have gotten the completed dataframe from the tidyr lesson. @juanfung says he'll handle this.
