### ISSUE TITLE
Fix inline r code in dplyr section

### ISSUE THREAD

**Issue by colinquirk** [datacarpentry/r-socialsci#138]
Good first issue?

In the dplyr episode (episode 03), there is a line that says

> View the interviews_items_owned data frame. It should have r nrow(interviews) rows (the same number of rows you had originally), but extra columns for each item.

which should read

> View the interviews_items_owned data frame. It should have 131 rows (the same number of rows you had originally), but extra columns for each item.

It is currently messed up due to a new line in the inline code:
https://github.com/datacarpentry/r-socialsci/blob/856ec2b513303d068931c056aebc6669c135dc18/_episodes_rmd/03-dplyr-tidyr.Rmd#L570

**Comment by juanfung** [comment]
Fixed #163
