### ISSUE TITLE
Fix "Improve this Page" links at tops of pages

### ISSUE THREAD

**Issue by angela-li** [datacarpentry/r-socialsci#148]
Will need to pull in updates from lesson template, so new PRs come in on master, and not gh-pages (change in #116)

**Comment by fmichonneau** [comment]
The instructions to update to the latest version of the template.

This assumes that `upstream` is set to the "official" repository for this lesson and `origin` is your fork.


```shell
# make sure the repo is up to date
git pull upstream master
# create a new branch
git checkout -b update-styles
# bring in the latest version of the template
git pull git@github.com:carpentries/styles.git # or git pull https://github.com/carpentries/styles.git if you're not using SSH
# check for possible merge conflicts
git status
# resolve the possible merge conflicts
git push origin update-styles
```

Go to GitHub and open a pull request from your fork using the update-styles branch.
