### ISSUE TITLE
Calling all instructors: Update our instructor notes!

### ISSUE THREAD

**Issue by angela-li** [datacarpentry/r-socialsci#149]
Have you taught this lesson? One way you can help us improve it is by filing issues here about typos you've discovered, but you can also help us fill out the [instructor notes](https://datacarpentry.org/r-socialsci/guide/index.html)! 

- What did you find difficult? 
- Where was it too fast? 
- What exercises could be improved? 
- What did learners struggle with? 
- What did you emphasize? What did you cut out?
- And much more!

Add your notes into the Instructor Notes [here](https://github.com/datacarpentry/r-socialsci/edit/master/_extras/guide.md)!

**Comment by juanfung** [comment]
Closing issue, as instructor notes continue to evolve and issue not needed
