### ISSUE TITLE
Nonexistent data frame column ("split_items")

### ISSUE THREAD

**Issue by benbossc** [datacarpentry/r-socialsci#159]
```
interviews_items_owned <- interviews %>%
  separate_rows(items_owned, sep=";") %>% 
  mutate(items_owned_logical = TRUE) %>%
  spread(key = items_owned, value = items_owned_logical, fill = FALSE)
```
1) In "Introducing dplyr and tidyr," specifically code related to "Applying spread() to clean our data" (see above), the notes mention that implementing spread() switches from long format to wide format, creating "a new column for each of the unique values in the **split_items** column and fills those columns with TRUE or FALSE." **Split_items** is not an actual new column but refers to unique logical columns derived from the separate_rows function (i.e., car, computer, cow_cart, etc.). This should be clarified/made clearer.

**Comment by juanfung** [comment]
@benbossc Thank you for pointing this out! It looks like this was fixed in #104. The text now reads

> This creates a new column for each of the unique values in the items_owned column, and fills those columns with TRUE or FALSE.
