### ISSUE TITLE
Conflicting or missing versions of R requirements noted

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/r-socialsci#164]
On [this page](https://datacarpentry.org/r-socialsci/setup.html) it notes that you should have at least  R 3.3.1.

However on [this page](https://datacarpentry.org/socialsci-workshop/setup-r-workshop.html) it notes that you should have R 3.5.1.

Also, in both cases, it is only in the Linux instructions that a minimum R version is specified at all.

**Comment by juanfung** [comment]
I'm combining #188 and #164: 
---
@maneesha commented on Jan 23

In the [Guide](https://datacarpentry.org/r-socialsci/guide/) section, there is information on troubleshooting multiple R installs.   

It says:

> We are currently using R 3.x.y

I'm guessing this should be replaced with the actual version of R required for this lesson.  Note that [other documentation](https://github.com/datacarpentry/r-socialsci/issues/164) has conflicting information about what version of R to use.

**Comment by juanfung** [comment]
@maneesha Thank you for opening this important issue. 

Labeling this help wanted for now. It would be great if someone could go through the lesson and double check what the minimum version of R is required. Note that per #104, the minimum `tidyr` is 1.0.0. Not sure if that matters for backward compatibility.

**Comment by laurabotzet** [comment]
I went through the lesson and double checked all packages for their R version requirement. 

tidyverse (readr, tidyr, dplyr, ggplot2, jsonlite): R (>= 3.2)
lintr: R (>= 3.2)
lubridate: R (>= 3.2)
extrafont: R (>= 2.15)

The current version of tidyr (1.0.2) depends on R (>= 3.1). 

Therefor, I would say that the minimum version of R for this lesson is currently 3.2.

**Comment by juanfung** [comment]
@laurabotzet Awesome! Thank you for getting to the bottom of this. Do you want to submit a PR to update this? If not I can take care of it tmw. Thanks!!

**Comment by juanfung** [comment]
@maneesha The guide and setup files have been updated. Not sure if you've already opened an issue about this on the workshop page, but closing this as resolved.
