### ISSUE TITLE
Conflicting instructions on what packages to install

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/r-socialsci#165]
On [this page](https://datacarpentry.org/socialsci-workshop/setup-r-workshop.html) Linux users are instructed to install the `tidyverse` and `SQLite` packages.  Mac and Windows users are not instructed to install any packages.

On [this page](https://datacarpentry.org/r-socialsci/setup.html) *all* users are instructed to install `tidyverse` only.

**Comment by juanfung** [comment]
@maneesha Good point. We don't use `SQLite` in the R lesson. But it looks like the first link you posted is for the larger social science workshop page.  Please open this issue there: https://github.com/datacarpentry/socialsci-workshop/issues
