### ISSUE TITLE
"Improve this page" takes you to .md (not .rmd) editing page

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/r-socialsci#176]
Clicking on "Improve this page" from a lesson page takes you to the generated .md file, not the .rmd file that is supposed to be edited.  Since the .rmd file is the one that's supposed to be edited, this should take  you to the .rmd file instead.  This way users won't accidentally edit the .md file instead (as I just did a couple of times! :disappointed: )

@fmichonneau  This may be an issue for the lesson template rather than this lesson itself.

**Comment by fmichonneau** [comment]
this will be fixed once #154 is merged.

**Comment by angela-li** [comment]
Just merged #154, thanks all for your patience! Busy last few months...
