### ISSUE TITLE
ggplot graphs show proportions, not percents

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/r-socialsci#179]
In the ggplot lesson, we teach how to generate a bar chart showing proportion of residents who are part of an irrigation association, own certain items, etc.

The output graphics show the y-axis labels showing percents, but they actually show proportions.  For example, the y-ticks are 0.2, 0.4, 0.6, etc.  To show percents, it should be 20%, 40%, 60%, etc.  I would suggest changing the y-axis labels to "Proportion" rather than "Percent."  Alternatively, we could introduce how to multiply the y-tick labels by 100 so they actually reflect percents.

**Comment by juanfung** [comment]
Resolved by #198
