### ISSUE TITLE
missing link for dataset description (7577)

### ISSUE THREAD

**Issue by ha0ye** [datacarpentry/r-socialsci#18]
In episode 02, there's supposed to be a link to a description of the example dataset:
```
Full details of the SN7577 dataset are available [here]
```
but the URL is missing. I'm not sure what this is supposed to be, so I'm leaving it blank for my current batch of reformatting edits.

It's possible that this information should also be added to the https://github.com/datacarpentry/python-socialsci lesson, too.

**Comment by juanfung** [comment]
@ha0ye Nice detective work! Resolved by ef0f3d254b5e674a1c90a8c5cecd83395ffcc049
