### ISSUE TITLE
Suggestions for "R and RStudio setup page"

### ISSUE THREAD

**Issue by kerstinlenk** [datacarpentry/r-socialsci#186]
Hi,

On the R and RStudio setup page (https://datacarpentry.org/r-socialsci/setup.html), I would suggest to
- add a sentence about the tidyverse package at the beginning of the page. For example: The tidyverse package is a powerful collection of data science tools within R (https://tidyverse.tidyverse.org).
- add an "or" between the two bullet points in the section "If you already have R and RStudio installed" for both Windows and Mac. In my opinion, they are alternatives and one does not have to do both.

Best regards
Kerstin

**Comment by juanfung** [comment]
Thanks @kerstinlenk ! ec0c8b4b addresses your first point. As to your second point if I understand correctly the instructions are for updating RStudio and R separately. I don't believe RStudio updates R? Closing for now but please let me know if you want to reopen.

**Comment by kerstinlenk** [comment]
Thanks @juanfung ! My comment referred to something else but as it seems it is already solved :)

**Comment by juanfung** [comment]
Perfect!
