### ISSUE TITLE
"Guide" section does not refer to a specific version of R

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/r-socialsci#188]
In the [Guide](https://datacarpentry.org/r-socialsci/guide/) section, there is information on troubleshooting multiple R installs.   

It says:

> We are currently using R 3.x.y

I'm guessing this should be replaced with the actual version of R required for this lesson.  Note that [other documentation](https://github.com/datacarpentry/r-socialsci/issues/164) has conflicting information about what version of R to use.

**Comment by juanfung** [comment]
@maneesha Thank you for opening this and #164. This is an important issue. 

Labeling this help wanted for now. It would be great if someone could go through the lesson and double check what the minimum version of R is required. Note that per #104, the minimum `tidyr` is 1.0.0. Not sure if that matters for backward compatibility.

**Comment by juanfung** [comment]
See #164
