### ISSUE TITLE
Is this lesson in beta?

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/r-socialsci#189]
The [Data Carpentry lessons page](https://datacarpentry.org/lessons/) lists this lesson among the standard offerings, and does not say it is in a beta or pilot phase.  

However, there is an overlay on each Social Science lesson page that notes it is piloted / in beta.

See example: 
![image](https://user-images.githubusercontent.com/829690/73002520-32a01580-3dd2-11ea-9ee7-5929eea3117f.png)

**Comment by fmichonneau** [comment]
yes the social science curriculum is in beta (and the python and SQL lessons are still in alpha). We can reconsider this but I think that in the past we only listed lessons that are in alpha (and pre-alpha) under "lessons under development and consideration" on the lesson page.

**Comment by juanfung** [comment]
Closing this
