### ISSUE TITLE
missing SPSS version of the data file

### ISSUE THREAD

**Issue by ha0ye** [datacarpentry/r-socialsci#19]
One of the exercises in episode 02 refers to loading the data from an SPSS output file.
```
Use the import dataset wizard to import the SN7577_spss.sav dataset.
```
 I didn't find this file in the `data` subfolder or in the python version of the lesson. Does this need to be added to the repo?

**Comment by PeterSmyth12** [comment]
[SN7577_spss.zip](https://github.com/datacarpentry/r-socialsci/files/1948743/SN7577_spss.zip)

zipped version of SN7577_spss.sav

**Comment by juanfung** [comment]
Data added in 3042717ad499084d6ac0aeb25884001630b3b180
