### ISSUE TITLE
Broken link to data in JSON lesson

### ISSUE THREAD

**Issue by timcashion** [datacarpentry/r-socialsci#202]
In the opening paragraphs of the JSON Lesson, the link to the datafile is broken:

<img width="1188" alt="Screen Shot 2020-04-24 at 1 12 07 PM" src="https://user-images.githubusercontent.com/20193108/80253315-e1502e00-862d-11ea-93be-d390b357f58d.png">

Data file missing is SAFI.json.

Lesson link: https://datacarpentry.org/r-socialsci/0x-json/index.html

Data expected to be found in 'r-socialsci/data/SAFI.json'

Hopefully a small fix! 

Thanks,

Tim

**Comment by fmichonneau** [comment]
fixed with a93e728
