### ISSUE TITLE
Clarifying "Introducing dplyr and tidyr" episode

### ISSUE THREAD

**Issue by roblevenson** [datacarpentry/r-socialsci#217]
Two comments:

1) The beginning of the episode on dplyr and tidyr repeats information about R packages that is also at the end of the “before we start” episode. I suggest removing the repetitive material from the dplyr episode.

2) The section on long and wide data structures does not provide an explicit introduction to long and wide data formats, but instead refers to a separate lesson. This section could benefit from an introduction like that in the “Dataframe manipulation with tidyr” lesson in “R for Reproducible Scientific Analysis”

**Comment by juanfung** [comment]
@roblevenson Thank you for the suggestions. These are great points, especially point 1, which I think I can easily fix. 

Would you like to submit a PR that addresses point 2? If not, no worries. I can chat with the other maintainers about the best way to address this.

**Comment by kelseygonzalez** [comment]
@juanfung it seems like you've made a commit to fix this issue but did not close the issue. Please reopen if you're still working on it!

**Comment by juanfung** [comment]
@kelseygonzalez Yes, I neglected to mention that 2 is being addressed in a rework of `pivot_wider` and `pivot_longer` by @atheobold
