### ISSUE TITLE
Delorean reference may not be globally accessible

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/r-socialsci#223]
In the R intro lesson, there is a metaphor that compares R and R Studio to an ordinary Delorean and the Delorean time machine.  While it's a clever reference for those who may understand it, it is referencing an American movie that is over 30 years old.  This may not be understandable and accessible to a global audience.  I am opening this up for discussion; I'm curious to know what other people think.

**Comment by atheobold** [comment]
Thanks for the suggestion @maneesha! Honestly, I didn't know that the car was a Delorean, which I think reiterates your point. Based on the pictures, it seems that the lesson is intending to covey the message that (1) R is fast, and (2) RStudio has lots of cool extras for working in R. Maybe we could covert this message to be more modern with the use of a car familiar to most people? I'm not a car fanatic, so any suggestions you have would be welcome!

**Comment by juanfung** [comment]
I guess the question is whether the images convey (1) and (2), which they probably don't. I also wonder if (1) is supposed to convey fast (just opening up the question). 

If we do update the pictures, we don't need to use another car though! How about an old school television vs a smart tv? Or it could even be a radio vs a television. 

If we do use cars, the images should convey the message clearly. So maybe just a sports car vs a race car?

**Comment by atheobold** [comment]
@juanfung I suppose I came up with the idea "`R` is fast" from my experiences hearing the comparison of `R` as a race car, and SAS as a bus. I like the idea of converting the comparison to televisions. We could choose a television from the 1990s (when `R` was created) to contrast against a modern smart television!

**Comment by juanfung** [comment]
@atheobold Ha! I love the analogy of SAS as a bus. 

I like the 1990s tv idea! Although I don't mean it to suggest R is intrinsically "slow" or "outdated technology."

**Comment by atheobold** [comment]
@juanfung I do agree that we want to make sure that people don't interpret the pictures as `R` being slow or outdated. I'm not quite sure how to convey the message that `R` is a very computationally efficient language, but coding in R (instead of RStudio) feels outdated.

**Comment by juanfung** [comment]
Recording per discussion w @atheobold and @kelseygonzalez ... Maybe a 'dumb' phone vs a smart phone?

**Comment by maneesha** [comment]
I think the phone analogy may have the same drawback of the TV analogy - that the old phone is slow and outdated.  

Do other people think there is an obvious purpose to the images?

**Comment by kelseygonzalez** [comment]
@maneesha we discussed this a bit in our meeting today and my opinion is that the images don't serve a specific useful purpose and similar lessons in DC and SWC don't go through the differences between R and Rstudio. I vote to remove them as they are not contributing to the lesson content and may reduce inclusion through alienation for those who don't understand the reference. I'm not sure if I convinced @atheobold or @juanfung, though. I believe we're letting the ideas for better analogies percolate for the time being.

**Comment by juanfung** [comment]
I'm okay with removing it *for now*. But I also see value in thinking about an alternative. It doesn't seem other lessons spend much, if any, time making the distinction between R and the IDE and it would be nice to be able to address it. As we discussed in our meeting, learners are often confused about the difference between the two. Installing RStudio without R is not uncommon. 

So addressing this point is probably worthwhile. At least, personally I prefer that to giving up because it's not as straightforward as I thought haha

**Comment by juanfung** [comment]
per discussion with @atheobold and @kelseygonzalez , replacing with image of manual vs automatic transmission

**Comment by juanfung** [comment]
How about these?

manual: https://unsplash.com/photos/D19rXKDUPYM

automatic: https://unsplash.com/photos/Wec3M4dY_LE

**Comment by kelseygonzalez** [comment]
I think those are similar enough that I'm happy, @juanfung , thanks for searching!

**Comment by atheobold** [comment]
Those are similar enough that I think they get the point across. As an aside, it would have been __way__ easier to learn to drive a manual if there were slots for each gear!

**Comment by juanfung** [comment]
@atheobold YES!
