### ISSUE TITLE
replace width with length in exercise

### ISSUE THREAD

**Issue by cengel** [datacarpentry/r-socialsci#227]
Second exercise on "Introduction to R" Page https://datacarpentry.org/r-socialsci/01-intro-to-r/index.html should replace width with length

... It should be noted that R Studio might add “()” after **width** and if you leave the parentheses you will get unexpected results..

Correct to 
... It should be noted that R Studio might add “()” after **length** and if you leave the parentheses you will get unexpected results..

**Comment by juanfung** [comment]
Resolved 19520f0
