### ISSUE TITLE
Error in code that generate `interviews_plotting` table

### ISSUE THREAD

**Issue by cengel** [datacarpentry/r-socialsci#228]
Episode  03-dplyr-tidyr.Rmd:  the code that generates the output for the plotting table line 695 causes an error. 

    Error: Can't rename columns that don't exist.
    x Column `NA` doesn't exist.

It seems to me that the line can just be removed.

    interviews_plotting <- interviews %>%
        ## pivot wider by items_owned
        separate_rows(items_owned, sep=";") %>%
        mutate(items_owned_logical = TRUE) %>%
        pivot_wider(names_from = items_owned, 
                    values_from = items_owned_logical, 
                    values_fill = list(items_owned_logical = FALSE)) %>%
        rename(no_listed_items = `NA`) %>%     ## <<<<==== ERROR
        ## pivot wider by months_lack_food
        separate_rows(months_lack_food, sep=";") %>%
        mutate(months_lack_food_logical = TRUE) %>%
        pivot_wider(names_from = months_lack_food, 
                    values_from = months_lack_food_logical, 
                    values_fill = list(months_lack_food_logical = FALSE)) %>%
        ## add some summary columns
        mutate(number_months_lack_food = rowSums(select(., Jan:May))) %>%
        mutate(number_items = rowSums(select(., bicycle:car)))

**Comment by juanfung** [comment]
Thank you, @cengel. I cannot reproduce your error. The column is renamed and I can inspect it:
```
> interviews_plotting <- interviews %>%
+     ## pivot wider by items_owned
+     separate_rows(items_owned, sep=";") %>%
+     mutate(items_owned_logical = TRUE) %>%
+     pivot_wider(names_from = items_owned,
+                 values_from = items_owned_logical,
+                 values_fill = list(items_owned_logical = FALSE)) %>%
+     rename(no_listed_items = `NA`) %>%
+     ## pivot wider by months_lack_food
+     separate_rows(months_lack_food, sep=";") %>%
+     mutate(months_lack_food_logical = TRUE) %>%
+     pivot_wider(names_from = months_lack_food,
+                 values_from = months_lack_food_logical,
+                 values_fill = list(months_lack_food_logical = FALSE)) %>%
+     ## add some summary columns
+     mutate(number_months_lack_food = rowSums(select(., Jan:May))) %>%
+     mutate(number_items = rowSums(select(., bicycle:car)))
> interviews_plotting %>% dplyr::select(no_listed_items)
# A tibble: 131 x 1
   no_listed_items
   <lgl>
 1 FALSE
 2 FALSE
 3 FALSE
 4 FALSE
 5 FALSE
 6 TRUE
 7 FALSE
 8 FALSE
 9 FALSE
10 FALSE
# … with 121 more rows
```

**Comment by atheobold** [comment]
I was also unable to reproduce the error you obtained @cengel.

**Comment by kelseygonzalez** [comment]
I test this as well on my machine and failed to produce the error. I am unsure why @cengel got the error, but my best guess is a dplyr, tidyr, or R version difference.  Let us know if you're able to recreate the error or debug. Thanks for the contribution, @cengel !

**Comment by juanfung** [comment]
I was able to reproduce @cengel's error. The strange thing is nothing has changed, except that I started a fresh session. The problem turns out to be that `pivot_wider` creates a new column called `NULL` rather than `NA`.

```
> interviews = read_csv('data/SAFI_clean.csv')
Parsed with column specification:
cols(
  key_ID = col_double(),
  village = col_character(),
  interview_date = col_datetime(format = ""),
  no_membrs = col_double(),
  years_liv = col_double(),
  respondent_wall_type = col_character(),
  rooms = col_double(),
  memb_assoc = col_character(),
  affect_conflicts = col_character(),
  liv_count = col_double(),
  items_owned = col_character(),
  no_meals = col_double(),
  months_lack_food = col_character(),
  instanceID = col_character()
)
> interviews %>%
+     separate_rows(items_owned, sep=";") %>%
+     mutate(items_owned_logical = TRUE) %>%
+     pivot_wider(names_from = items_owned,
+                 values_from = items_owned_logical,
+                 values_fill = list(items_owned_logical = FALSE))
# A tibble: 131 x 31
   key_ID village interview_date      no_membrs years_liv respondent_wall… rooms
    <dbl> <chr>   <dttm>                  <dbl>     <dbl> <chr>            <dbl>
 1      1 God     2016-11-17 00:00:00         3         4 muddaub              1
 2      1 God     2016-11-17 00:00:00         7         9 muddaub              1
 3      3 God     2016-11-17 00:00:00        10        15 burntbricks          1
 4      4 God     2016-11-17 00:00:00         7         6 burntbricks          1
 5      5 God     2016-11-17 00:00:00         7        40 burntbricks          1
 6      6 God     2016-11-17 00:00:00         3         3 muddaub              1
 7      7 God     2016-11-17 00:00:00         6        38 muddaub              1
 8      8 Chirod… 2016-11-16 00:00:00        12        70 burntbricks          3
 9      9 Chirod… 2016-11-16 00:00:00         8         6 burntbricks          1
10     10 Chirod… 2016-12-16 00:00:00        12        23 burntbricks          5
# … with 121 more rows, and 24 more variables: memb_assoc <chr>,
#   affect_conflicts <chr>, liv_count <dbl>, no_meals <dbl>,
#   months_lack_food <chr>, instanceID <chr>, bicycle <lgl>, television <lgl>,
#   solar_panel <lgl>, table <lgl>, cow_cart <lgl>, radio <lgl>,
#   cow_plough <lgl>, solar_torch <lgl>, mobile_phone <lgl>, motorcyle <lgl>,
#   `NULL` <lgl>, fridge <lgl>, electricity <lgl>, sofa_set <lgl>, lorry <lgl>,
#   sterio <lgl>, computer <lgl>, car <lgl>
```
as seen in the second to last line above. So now the question is why I got an `NA` column last week and a `NULL` column this week. Can anyone else reproduce?

Session info (in summary, R 4.0.2 and tidyverse 1.3.0):
```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] forcats_0.5.0   stringr_1.4.0   dplyr_1.0.0     purrr_0.3.4
[5] readr_1.3.1     tidyr_1.1.0     tibble_3.0.2    ggplot2_3.3.2
[9] tidyverse_1.3.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5       pillar_1.4.4     compiler_4.0.2   cellranger_1.1.0
 [5] dbplyr_1.4.4     tools_4.0.2      jsonlite_1.7.0   lubridate_1.7.9
 [9] lifecycle_0.2.0  gtable_0.3.0     pkgconfig_2.0.3  rlang_0.4.6
[13] reprex_0.3.0     cli_2.0.2        rstudioapi_0.11  DBI_1.1.0
[17] haven_2.3.1      withr_2.2.0      xml2_1.3.2       httr_1.4.1
[21] fs_1.4.2         generics_0.0.2   vctrs_0.3.1      hms_0.5.3
[25] grid_4.0.2       tidyselect_1.1.0 glue_1.4.1       R6_2.4.1
[29] fansi_0.4.1      readxl_1.3.1     modelr_0.1.8     blob_1.2.1
[33] magrittr_1.5     backports_1.1.8  scales_1.1.1     ellipsis_0.3.1
[37] rvest_0.3.5      assertthat_0.2.1 colorspace_1.4-1 stringi_1.4.6
[41] munsell_0.5.0    broom_0.7.0      crayon_1.3.4
```

**Comment by juanfung** [comment]
Well that was easy: at the beginning of episode 3, when loading the SAFI data, we tell `read_csv` that "NULL" values should be treated as `NA`:
```
interviews <- read_csv("data/SAFI_clean.csv", na = "NULL")
```
If a learner quickly re-loads the data without doing this (as I did), they will have a `NULL` column rather than `NA` column. 

Will this create confusion?

**Comment by kelseygonzalez** [comment]
I think we should assume learners are going through the lesson and/or website fully from beginning to end. We could, however, write a side note saying that if you get "this column doesn't exist" as an error, it's because you're data frame has NULL / NA mixed. I've had similar errors where learners use read.csv() instead of read_csv() and these tiny errors really trip them up.

**Comment by atheobold** [comment]
@juanfung -- I agree with @kelseygonzalez that we should assume that learners are going through the material from beginning to end. But, adding a note to the instructor notes that mentions this error would certainly be helpful! 

@cengel would you be interested in contributing a note explaining this error to the instructor notes for this lesson? The instructor notes can be found [here](https://datacarpentry.org/r-socialsci/guide/index.html).
