### ISSUE TITLE
solution throws error

### ISSUE THREAD

**Issue by cengel** [datacarpentry/r-socialsci#233]
Episode : 02-starting-with-data.Rmd

The division by 2 in the solution to question 3 in the exercises on subsetting causes an error, because the total number of rows in the data file (131) results in 65.5

Line 262:

    interviews_middle <- interviews[(n_rows / 2), ]`

Results in:

    Error: Must subset rows with a valid subscript vector.
    ✖ Can't convert from <double> to <integer> due to loss of precision.

**Comment by juanfung** [comment]
Thank you @cengel ! I can think of several alternatives
1. Integer division `%/%`
2. Round, ie, `round(n_rows / 2)`
3. Floor or ceiling, eg, `floor(n_rows /2)` 
I'm not sure which is the best in terms of teaching. Maybe `round`? Might be worth keeping as is, showing the error, and introducing `round`

Paging @kelseygonzalez and @atheobold

**Comment by kelseygonzalez** [comment]
I'm leaning towards adding a "Hint: you may need to use the `round()` function to accomplish this!" at the end of that exercise step.

**Comment by atheobold** [comment]
Great find @cengel! I think the exercise can be scaffolded a bit better, to prompt learners to expect that finding the middle row may require a bit more thought. Also, like @kelseygonzalez I am inclined to add a hint.

Alternatively, I would advocate the use of `R`'s built-in `median( )` function over `round( )`, since this function doesn't require that we discuss the default behavior of `round( )` when a `digits` argument is not provided. 

My revised prompt and solution would be: 

> Using the number of rows in the interviews dataset that you found in question 2, extract the row that is in the middle of the dataset. Store the content of this middle row in an object named `interviews_middle`.
> 
> __Hint:__ This dataset has an odd number of rows, so finding the middle is a bit trickier than dividing `n_rows` by 2. Use the `median( )` function and what you've learned about sequences in `R` to extract the middle row! 
> 

`interviews_middle <- interviews[median(1:nrow(interviews)), ]`

**Comment by kelseygonzalez** [comment]
I like this solution, @atheobold . I wonder if students will be able to come up with 1:nrow(interviews) with a less thorough introduction to this sort of vectorization in the earlier section of this episode than in other curricula. There is a section with the following prose, which should provide a strong enough foundation: `: is a special function that creates numeric vectors of integers in increasing or decreasing order, test 1:10 and 10:1 for instance.` (around line 200 in the .rmd)

@juanfung do you think the section on `:` is sufficient scaffolding to arrive at @atheobold 's solution?

**Comment by atheobold** [comment]
I think that the introduction to the `:` function belongs more in the Introduction to R section, potentially in the Subsetting Vectors section. If we add this and give an example of extracting a sequence of indices from a vector, I think that referencing this in the exercise wouldn't be that large of a stretch.

**Comment by juanfung** [comment]
@atheobold I do like the use of median with the hint. And I agree that the discussion on `:` would fit in well under subsetting vectors. in the software carpentry lessons, this is part of the first "real" episode on Data Structures (specifically the section on vectors!)

**Comment by atheobold** [comment]
@juanfung - great! I think we can simply add @kelseygonzalez's text to the subsetting vectors section. @kelseygonzalez - would you like to make this addition?

I am happy to make the change to the "solution" for the exercise that uses the `median()` function in the hint.

**Comment by juanfung** [comment]
@atheobold That text already exists in episode 2. Moving it would require introducing `:` earlier, not difficult but not straightforward. Or we leave it where it is. I'm okay either way

**Comment by atheobold** [comment]
@juanfung I didn't realize that the text @kelseygonzalez provided was verbatim from episode 2. Let's leave it be!
