### ISSUE TITLE
Add link to SAFI data in Setup

### ISSUE THREAD

**Issue by juanfung** [datacarpentry/r-socialsci#247]
It would be convenient to find the link to the data in setup.

Alternatively, setup could point to episode 00 for download instructions

**Comment by juanfung** [comment]
@atheobold @kelseygonzalez Never realized it but link to data is already at the top of the [Instructor Notes](https://datacarpentry.org/r-socialsci/guide/). Don't think we need it in setup too, do we?

**Comment by kelseygonzalez** [comment]
It never hurts to have instructions on how to get to it from all three locations, even if they're all pointing to one place.
