### ISSUE TITLE
Starting With Data > Data Wrangling: Reco to add a small snippet showing to convert character to date format

### ISSUE THREAD

**Issue by menghamo** [datacarpentry/r-socialsci#255]
In the example used, the dataset seems to be formatted with such that the read_csv function is able to read in the date column in correct format. Generally, that is not the case and date columns are often read in as character and need to be converted to date. I would recommend to add a small snippet simply highlighting how to convert character to date format. 

The lesson does mention use of ymd() but assuming the lesson is for beginner level users a small example like 

t <- c("7/31/2012","8/31/2014",'4/30/2106')
ymd(t)
mdy(t) or as_date(t, format = "%m/%d/%y")
ymd(mdy(t))

might be helpful.

**Comment by atheobold** [comment]
Hi @menghamo! I sincerely apologize for our delayed response, each of the maintainers have had a hectic week. I **really** like your suggestion, and agree that many (if not most) of the dates that people may need to wrangle will not be in this tidy format. 

Would you be interested in contributing this example to the lesson, to make the section on `lubridate` more robust?

**Comment by menghamo** [comment]
Oh no worries at all. Yes absolutely, I would be happy to!
