### ISSUE TITLE
Website build issues

### ISSUE THREAD

**Issue by juanfung** [datacarpentry/r-socialsci#258]
- Code output prints a bunch of weird stuff (seems to only be for data.frames/tibbles). See eg [episode 02](https://datacarpentry.org/r-socialsci/02-starting-with-data/index.html). 
> [90m# A tibble: 131 x 14 [39m
- PR checks failing because build-website is failing (specifically `Run make lesson-check`. See eg [this PR](https://github.com/datacarpentry/r-socialsci/pull/257/checks?check_run_id=1211346820)

@fmichonneau Tagging you in the hopes that you can help us out with these issues!

**Comment by fmichonneau** [comment]
Hi @juanfung 

Thanks for bringing this up.

I fixed the weird rendering of tables with eca3b3bbc449fa2365809e572813135ec2734efe and 4116d85fe5d240ac27f492b0c4d71ac31fa07493

I [commented](https://github.com/datacarpentry/r-socialsci/pull/257#issuecomment-704769235) in the thread about the build failure.

Please let me know if there are other things I can help with :smile:

**Comment by juanfung** [comment]
@fmichonneau Thank you for all your help!
