### ISSUE TITLE
Fixing minor issues with json episode

### ISSUE THREAD

**Issue by juanfung** [datacarpentry/r-socialsci#260]
- Episode is unnumbered. Does it make sense to number it 05, ie, directly after ggplot2? 
- Use of `write.csv` should be changed to `write_csv` top be consistent
- Object is coerced to data.frame. Should we coerce to tibble?
    - This would help with the massive amount of output from `head(json_data)`
    - Could use `glimpse(json_data)` instead, but not sure if we use in other episodes
- A less minor change, but not maybe not such a huge change, would be to use [`tidyjson`](/packages/tidyjson/vignettes/introduction-to-tidyjson.html) instead of (*or in addition to*) `jsonlite`

**Comment by atheobold** [comment]
I'd like to add `glimpse()` to the Starting with Data lesson, since the **tidyverse** is already installed. So, then having it in this lesson wouldn't be new.

**Comment by juanfung** [comment]
Tabling `tidyjson` for now as I don't see an obvious need
