### ISSUE TITLE
Discussion of key_id and instanceID confusing for pivoting

### ISSUE THREAD

**Issue by dafnevk** [datacarpentry/r-socialsci#263]
The section in [Episode 3](https://datacarpentry.org/r-socialsci/03-dplyr-tidyr/index.html) on Reshaping with pivot_wider() and pivot_longer() starts with observations about the key_id and instanceID and relates this to the long and wide format. I understand this text is added in response to issue #122, but I find it very confusing because it is not directly related to wide and long formats. In particular the following sentence:

>  As seen in the code below, for each interview date in each village no instanceIDs are the same. Thus, this format is what is called a “long” data format, where each observation occupies only one row in the dataframe.

This suggest that we are going to do a pivot with the instanceID as key and dates as column names. 
The accompanied GIF confuses me even more, because it shows multiple rows with the same key in the long format, suggesting that we will use key_ID to pivot on.

My suggestion is to edit the data description in episode 2 to note the instanceID should be used as unique identifier.
The section on wide and long formats can probably use a rewrite to introduce the concepts immediatly based on the dataset (such as with the very helpful image of going from long to wide with the wall types).

**Comment by dafnevk** [comment]
I think the concept of going from a long to a wide format is easier to explain using the result of a group_by, which is in long format. For example:
```R
interviews_grouped <- interviews %>%
  group_by(village, respondent_wall_type) %>%
  count()

# Inspect interviews_grouped to see that it is in long format

interviews_grouped %>% 
  pivot_wider(id_cols = village, 
              names_from = respondent_wall_type, 
              values_from = n)
```
(This is similar to how it is explained in the [Ecology lessson](https://datacarpentry.org/R-ecology-lesson/03-dplyr.html#Reshaping_with_gather_and_spread) )

**Comment by juanfung** [comment]
@dafnevk Thank you for the suggestions! You make a good point. Would you be interested in submitting a PR to implement your suggestions?

**Comment by dafnevk** [comment]
I will do that.

**Comment by atheobold** [comment]
Hi @dafnevk! Thanks for your input on the new content of this lesson. You are correct, the content was motivated by an issue, namely, Issue #217. The request was to create content that provided an explicit introduction to long and wide data formats, and how these formats might manifest in datasets researchers may work with. 

I agree that the description of long and wide data provided in the Ecology curriculum is simpler to understand, but I would argue that this section of our lesson has a different purpose. Personally, I have found that learners understand the differences between long and wide data, when introduced as the output of a `group_by()` statement. However, these same learners often struggle to identify which format a "real" dataset is in. Thus, the purpose of this new section is to describe what "long" and "wide" data formats look like in real data. 

Now, knowing the purpose we had in mind for this section, if you feel that the section could be more clear, please feel free to contribute!

**Comment by dafnevk** [comment]
Thanks @atheobold for the clarification.
I started with a rewrite and will do a pull request. I think it indeed good to keep in the part were we use `pivot_wider()` to do something actually useful for our dataset, but first explain the concept of longer and wider using the grouped dataframe.

**Comment by atheobold** [comment]
As I mentioned in my comment to PR #270, the "Introduction" section is intended to provide a big picture overview of what we mean by "long" and "wide" data formats, and how these formats look "in the wild."

While I agree that the `group_by()` - `summarize()` pipeline produces a "tidy" introduction to long and wide data formats, personally I feel quite dissatisfied with learners not leaving the lesson with a sense of being able to determine what format a dataset is in. Given, this need to orient learners to the bigger picture of these data formats, I would appreciate your input refining the existing long and wide data formats section.

If you feel that the "key" pieces of these data formats would be better conveyed with different variables or explorations, please feel free to contribute! Another thought to keep in the back of your mind is the possibility of us adding a section on working with relational data in dplyr. This section would explicitly discuss "keys" for datasets, which could be a good way to introduce what information we need from the interviews dataset to define a "unique" observation.
