### ISSUE TITLE
Introduce glimpse in "Starting with Data"

### ISSUE THREAD

**Issue by juanfung** [datacarpentry/r-socialsci#265]
Per #260, using `tibble::glimpse` to peek at parsed json tibble. It would be nice to introduce `glimpse` in Starting with Data episode.

**Comment by nataliablock** [comment]
It would be nice to introduce glimpse in the "inspecting data frames" section. I can work on that and send a PR if it's ok for you all.

**Comment by juanfung** [comment]
@nataliablock Thank you, that would be great!

**Comment by nataliablock** [comment]
I'm on it!
