### ISSUE TITLE
Purpose of `reference.md`

### ISSUE THREAD

**Issue by juanfung** [datacarpentry/r-socialsci#267]
This file was added Aug 2018, remains a TODO: https://github.com/datacarpentry/r-socialsci/blob/master/reference.md

The R ecology lesson uses this as a ["cheat sheet" of functions used in each episode](https://github.com/datacarpentry/R-ecology-lesson/blob/main/reference.md).

The R intro to geospatial lesson uses this as a bit of a more general ["cheat sheet"](https://github.com/datacarpentry/r-intro-geospatial/blob/master/reference.md).

The R geospatial raster and vector data lesson simply uses this as a [reference to useful sites](https://github.com/datacarpentry/r-raster-vector-geospatial/blob/master/reference.md).

Python social science lesson uses this as a [glossary](https://github.com/datacarpentry/python-socialsci/blob/gh-pages/reference.md).

In this lesson, we have a lot of this information (not all) scattered throughout the instructor notes, setup guide, and now even the very nice code handouts that @atheobold is developing.

So the question is, what if anything do we do with `reference.md`? Some ideas:

- Simplify instructor notes and setup by moving some of the material to reference
- Just glossary
- Just a list of links
- Discard it completely
- Other ideas?

**Comment by atheobold** [comment]
@juanfung -- it sounds like we have two votes in favor of transitioning to a similar purpose as the Ecology curriculum. Let's do it!

**Comment by juanfung** [comment]
To be clear, I didn't vote...I'm ambivalent 😝 I'd be okay with several of the options...but happy to turn into a glossary of functions used, if we think that is useful.

**Comment by juanfung** [comment]
I suppose I have reservations about using reference as a glossary of functions used. I've seen it used for packages, which makes a lot more sense to me since it's a reference of the functions *in the package*. Having never taught this workshop myself, do yall believe that having this would be useful to either the learners or to the instructors?
