### ISSUE TITLE
Broken Links to Code Handouts

### ISSUE THREAD

**Issue by atheobold** [datacarpentry/r-socialsci#274]
Under the "Extras" at the lesson website there are four links to Code Handouts, all of which have 404 errors when selected. Additionally, the handout labeled "Code Handout" should be labeled "Code Handout - Data Wrangling".

**Comment by kelseygonzalez** [comment]
My quick reaction is that the .Rmd files in the `_extras` folder don't seem to be getting knitted to `.md` or `.html`. I think we need ot investigate the website architecture to determine if there's a way to get these knitted or if we need to move them into a place where they will be properly rendered.

**Comment by fmichonneau** [comment]
yes, the `.Rmd` files in `_extras` are not knitted. We could address this in the lesson template. Before doing so, I'd like to clarify your goal with these files. Do you want them to look like a page of the website that workshop participants could copy and paste from, or do you expect these pages to be `.R` files that people could download from the site and open directly in RStudio (like the [code handout](https://datacarpentry.org/R-ecology-lesson/code-handout.R) from the R-ecology lesson?

**Comment by atheobold** [comment]
Hi all, 

Sorry for the short message, I was typing it as more of a note while going through our website. I suppose @kelseygonzalez and @juanfung and I can discuss what we think would be best way to present these files. When I created them I had envisioned them to render similar to the [reference page](https://datacarpentry.org/r-socialsci/reference.html), with the possibility of learners downloading the Rmd files, but I am open to other options.

**Comment by juanfung** [comment]
@atheobold I think the way you've written them, it would be nice to have them rendered, if it's not too difficult to do that

**Comment by kelseygonzalez** [comment]
Could we have them rendered as html (or even a pdf handout) and embed a link to download the .rmd file?

**Comment by atheobold** [comment]
I think that option would be my pick!

**Comment by atheobold** [comment]
@fmichonneau -- just checking in on how we can integrate these files as HTMLs on the Extras page with a link to download the Rmd file. Also, the ordering of items in the Extras menu seems to not be in any order that we can establish. Is there a way for us to control the order of items in this menu?

**Comment by AmandaDPerez** [comment]
@atheobold @kelseygonzalez you can render it as HTML and add in the yaml to allow download of the  .rmd as follows: 
output:
  html_document:
    code_download: true

**Comment by atheobold** [comment]
The "solution" proposed by @AmandaDPerez will produce a knitted HTML file with the option to download the RMarkdown file. However, the Rmd files inside the `_extras` folder are not getting knitted to HTML files (as seen [here](https://datacarpentry.org/r-socialsci/data-visualisation-handout/index.html)). 

@fmichonneau -- is there a way to get the Rmd files in the `_extras` folder to knit to HTML files?

**Comment by bencomp** [comment]
It looks like the Makefile should include the .Rmd files in `_extras` around 
https://github.com/datacarpentry/r-socialsci/blob/bc7c2a38276681ea850716e5beb4b4ae295787ca/Makefile#L102-L103 as well as https://github.com/datacarpentry/r-socialsci/blob/bc7c2a38276681ea850716e5beb4b4ae295787ca/Makefile#L129-L134 to have them knitted.

I don't know whether changing the Makefile for this lesson only is okay, or, as @fmichonneau mentioned, that it first has to be addressed in the lesson template and then here.

Thinking one step further, should the `_extras/*.Rmd` files be moved to a new `_extras_rmd/` folder, like the episodes? Or should the *knitted* `_extras/*.md` files be git-ignored explicitly to prevent them from being committed unintentionally?

But wait, there is more to adjust if the RMarkdown handouts are to be knitted to Markdown... I see that the knitting script expects the RMarkdown file to be in `_episodes_rmd/`:
https://github.com/datacarpentry/r-socialsci/blob/bc7c2a38276681ea850716e5beb4b4ae295787ca/bin/generate_md_episodes.R#L33
This line will not break the process, but it would point future lesson editors to the wrong place. To prevent this confusion, we could parse the path of the input file in `generate_md_episodes.R`, or duplicate that script to `generate_md_extras.R` and parse the input filepath in `knit_lessons.sh` to select the correct script.

All in all, I see ways to include RMarkdown files in `_extras`, but I wonder, err, how long the detour would take.

**Comment by juanfung** [comment]
@bencomp Thanks for your insights on fixing this issue! It sounds like these are higher level decisions that should be addressed in the lesson template. I'll discuss with the other maintainers about opening an issue or PR in https://github.com/carpentries/workshop-template

**Comment by atheobold** [comment]
Issue submitted to curriculum template repo: https://github.com/carpentries/workshop-template/issues/747

**Comment by livelyjing** [comment]
Can we use output: md_document in the rmd file to rent into md document and save the md documents in the _Extra folder to fix the issue?

**Comment by juanfung** [comment]
@livelyjing thank you for the suggestion! To be honest, I have no idea if that will fix it. Would you be willing to test that out on a local version of the repo (or you can serve using docker)?

**Comment by juanfung** [comment]
@zkamvar i wonder if you might be able to help with this issue. Basically, we created code handout `.Rmd` files, located in the `_extras` directory. They are not rendered to html because files in `_extras` are not knitted (per the Makefile). Any thoughts?

I did try @livelyjing's suggestion but that did not solve the problem.

**Comment by zkamvar** [comment]
Unfortunately, the way the styles template is set up, it's not possible to do this without manual intervention (i.e. rendering the files locally) or modifying the Makefile (which will cause problems updating the template in the future).

## potential solutions with the styles template

A least-amount-of-work solution is to do what https://swcarpentry.github.io/r-novice-gapminder/ did and place the handouts in the episodes dropdown, but clearly label them as extra content/handout.

Another potential stopgap solution would be to write a separate github action that builds the RMarkdown documents in the _extras folder whenever they are modified. If you have it in a separate file, it will not clash with the styles template. The only catch is telling the CI how to handle dependencies, which is still slightly nightmarish.


## future solutions

We will be running the beta phase of [The Carpentries Workbench](https://carpentries.github.io/sandpaper-docs) in April and will eventually transition the lessons once the beta phase is successful. The Workbench will render RMarkdown files anywhere in the lesson, so we won't have to worry about this missing feature. This means that you will be able to place custom handout documents in a folder called `learners/` and have it available for your learners to view/download.

I'm currently in the process of defining the expected outcomes and specific tasks for the beta phase participants and will send out a call for participants before April. If the maintainers of this lesson want to take part in the test, I'll be happy to convert this lesson in a sandbox repository so you can play around with it.

**Comment by tobyhodges** [comment]
Adding another possible solution for the current template: put the Rmd files in `_episodes` and use the optional manual episode ordering conifguration to prevent the knitted files from showing up in the Episodes dropdown or lesson navigation.

1. move the Rmd files to `_episodes`
2. add [an `episode_order` field to `_config.yml`](), listing all the proper episode files but leaving out the handout filenames

I have not been able to figure out a way to make these handouts then appear in the Extras menu, but I suppose you could include an Extra page that links to the pages created when the knitted versions of the Rmds are rendered by Jekyll? Or perhaps there is something you can do with redirects, that will automatically route someone from the page in extras to the handout created from episodes? ([The `jekyll-redirect-from` plugin](https://www.rubydoc.info/gems/jekyll-redirect-from/0.16.0) is included in GitHub Pages.)

**Comment by juanfung** [comment]
Thank you for the suggestions! I think for now the path of least resistance is to drop them into `_episodes_rmd` and label them as "extra" content. 

@zkamvar, very excited about the Workbench! Yes, I would love for this lesson to participate in the beta phase.

**Comment by zkamvar** [comment]
Hi @juanfung, the beta phase signup can be found here: https://github.com/carpentries/workbench/discussions/4

**Comment by juanfung** [comment]
@zkamvar thank you! just signed up

**Comment by atheobold** [comment]
The code handouts on the workbench look great! I wholeheartedly approve of the new layout, it looks great!

**Comment by juanfung** [comment]
@atheobold agreed! should we close this issue then?

**Comment by juanfung** [comment]
closing as this will be resolved with the new infrastructrure
