### ISSUE TITLE
Add link to download SAFI.json to Setup

### ISSUE THREAD

**Issue by jyoung22** [datacarpentry/r-socialsci#277]
I was running through the episodes and found that the setup for the R for Social Scientists lesson doesn't include a link to also download the SAFI data set as a JSON file. The beginning of episode 5 (Processing JSON data) does have a link, but it's not obvious. Currently, the link is embedded within a sentence in the opening blurb and the bolded piece is the entire link. 

> The JSON file we are going to use is the **SAFI.json** file.

It wasn't easy for my eyes to see that SAFI.json was the json file link (darker blues and blacks blend together for me). I kept referring back to the Setup and Before we Start episodes to see if I had missed the instructions for downloading the file.

I think adding this piece in to the Setup, or making the link more obvious (adding something like click this link to download the JSON data), would be ideal.

**Comment by juanfung** [comment]
@jyoung22 Great catch! If you'd like to submit a PR for this, let me know. If not, no worries - I will take care of it
