### ISSUE TITLE
Setup page is missing content

### ISSUE THREAD

**Issue by ljcohen** [datacarpentry/r-socialsci#28]
Page is blank, please add content!

http://www.datacarpentry.org/r-socialsci/setup/

**Comment by Epsian** [comment]
#30 Pull Request

**Comment by fmichonneau** [comment]
closed with #30

**Comment by benmarwick** [comment]
Seems that the setup page is missing content again: 

![image](https://user-images.githubusercontent.com/1262179/45353017-fb1d3880-b5e3-11e8-9f4d-95c45437017b.png)

**Comment by fmichonneau** [comment]
The URL for the setup instructions is https://datacarpentry.org/r-socialsci/setup.html

If there is a link somewhere in the lesson that points to http://www.datacarpentry.org/r-socialsci/setup/ please let me know!

**Comment by benmarwick** [comment]
Ah! I see, thanks, yes, I've made a PR to try to fix that: https://github.com/datacarpentry/r-socialsci/pull/85
