### ISSUE TITLE
Objectives in Data Visualisation with ggplot2 need to be updated

### ISSUE THREAD

**Issue by angela-li** [datacarpentry/r-socialsci#282]
In the lesson objectives for Data Vis with ggplot2, the Objectives say "time series plots" where it should say "barplots", since time series plots are not taught in the lesson. (The Questions are correct.): https://github.com/datacarpentry/r-socialsci/blob/bff25f5a69110ffb09710ae94126e3cfc13f1009/_episodes_rmd/04-ggplot2.Rmd#L11

This two-word change would be a great edit for a new contributor!

**Comment by lizawood5** [comment]
I'm looking for a good first issue, and this seems perfect. I have read the contributing guidelines and will submit a PR from my fork of this repo, but please let me know if I did something that doesn't align with the protocols.

Also a note is that in this lesson `geom_line` is listed as an item we will cover for time series (line 117) and `geom_bar` is not mentioned in that review. Being new to this contribution system, should I propose this as an issue?

**Comment by juanfung** [comment]
@lizawood5 Yes that would be a good issue or even better you can submit a PR! :)
