### ISSUE TITLE
Build site is failing

### ISSUE THREAD

**Issue by juanfung** [datacarpentry/r-socialsci#294]
Build site (and thus Deploy site) is failing. In particular, it looks to be the `make lesson-check` run, about where it tries to load 'stringi` via `knitr`:

> The downloaded source packages are in
	‘/tmp/RtmpKdteQo/downloaded_packages’
Loading required package: knitr

> processing file: _episodes_rmd/02-starting-with-data.Rmd
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/runner/work/_temp/Library/stringi/libs/stringi.so':
  libicui18n.so.60: cannot open shared object file: No such file or directory
Calls: source ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
Execution halted
make: *** [Makefile:131: _episodes/02-starting-with-data.md] Error 1
Error: Process completed with exit code 2.

We (the maintainers) are stumped!

**Comment by juanfung** [comment]
@zkamvar You mentioned changing 'master' to 'main' - how do we do that?

**Comment by zkamvar** [comment]
I can change that for you! It's in Settings > Branches > Default Branch > Rename Branch (:pencil2:)

**Comment by zkamvar** [comment]
Done!

You should now see a prompt when you visit the repo that the default branch is changed with the following instructions to update your local clone:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

**Comment by juanfung** [comment]
@zkamvar Thank you!

**Comment by zkamvar** [comment]
From https://github.com/datacarpentry/r-socialsci/commit/3e8345ba44e19516cc71c516238748fccdc0e61b, I can see that the build process is no longer failing and I think this issue can be closed.

**Comment by juanfung** [comment]
Thanks that's great! 

Do you know why some of the PRs that we merged last week when the build/deploy fell apart, aren't showing up?

Example: https://github.com/datacarpentry/r-socialsci/pull/288 is merged but does not show up on rendered website

**Comment by zkamvar** [comment]
@juanfung I think they don't show up because the PR was merged despite the checks not passing. 

Because the makefile only checks the modification time, it did not see those previously modified files as changed and did not rebuild them. Browsing the files in https://github.com/datacarpentry/r-socialsci/tree/a9143719fd0ea7e0bf52fcf10f807b5329624225/_episodes, you can see that the first two episodes were not rebuilt. This can be fixed by making a small change to these episodes in a new PR.

**Comment by juanfung** [comment]
@zkamvar Thank you! So there is no problem making these small changes directly to the .md files?

**Comment by zkamvar** [comment]
It would be better to make changes to the Rmd files

**Comment by juanfung** [comment]
That's what I figured. The problem is these changes are already in the Rmd files. For example, #288 is here: https://github.com/datacarpentry/r-socialsci/blob/7dab2aa18e9393c2e75e59c8c6a3fcead7e15900/_episodes_rmd/00-intro.Rmd#L133

**Comment by zkamvar** [comment]
I mean, you can make a _small_ change to the file. something like adding an extra line at the bottom of the file.

**Comment by zkamvar** [comment]
Well #296 has been merged and yet it remains unchanged. It definitely was built in the build process, and I am unsure of why it was not updated by git even though it definitely changed. I'll have to take a look at this tomorrow, unfortunately.

**Comment by juanfung** [comment]
@zkamvar Thank you, much appreciated!

**Comment by zkamvar** [comment]
I FOUND THE ISSUE!!!!! This should be "fig.cap" not "fig.caption"

https://github.com/datacarpentry/r-socialsci/blob/b963ccd383229c74b7111e66c4884ee952df3b13/_episodes_rmd/00-intro.Rmd#L132-L134

In fact, as of knitr version 1.31, there is the fig.alt option, which will give a better result.

**Comment by zkamvar** [comment]
I'm going to create a PR to fix this.

**Comment by kelseygonzalez** [comment]
You're a ⭐ @zkamvar . I think the issues are now all solved - thanks for your time and dedication to this.

**Comment by juanfung** [comment]
Amazing. Thank you @zkamvar !

**Comment by zkamvar** [comment]
Thank YOU both for your patience with this!
