### ISSUE TITLE
Definition of what a function is in Introduction to R episode

### ISSUE THREAD

**Issue by JFormoso** [datacarpentry/r-socialsci#298]
Hi!

I noticed that at the beginning of the episode (https://datacarpentry.org/r-socialsci/01-intro-to-r/index.html), when talking about how to create an object, we tell the participants that "There are some names that cannot be used because they are the names of fundamental functions in R (e.g., if, else, for, see here for a complete list). In general, even if it’s allowed, it’s best to not use other function names (e.g., c, T, mean, data, df, weights)" but we have not introduced what a function is yet. I found that when the audience has no previous experience with any programming language this generates some confusion. I think that giving a brief and generic explanation of what a function is while saying this, or the other way around, talking about what names not to use when creating an object after the functions section may help.

**Comment by juanfung** [comment]
@JFormoso Thanks for this observation! I like the latter option, ie, not introducing functions just yet, and maybe saying something like "these names are reserved for pre-defined objects in R that you will meet later [INSERTLINK?]"

But open to discussion! @kelseygonzalez @atheobold thoughts?

**Comment by atheobold** [comment]
@JFormoso & @juanfung -- I agree that talking about "functions" before they are introduced isn't great practice. I would be okay with @juanfung's revision of substituting the word "function" for "object," as these are simply reserved names for objects (which happen to be functions). 😃

**Comment by juanfung** [comment]
@JFormoso would you be willing to submit a small PR to make this change?

**Comment by JFormoso** [comment]
Yes! :D

**Comment by juanfung** [comment]
Great thank you!
