### ISSUE TITLE
possible change in tibbe behavior?

### ISSUE THREAD

**Issue by elliewix** [datacarpentry/r-socialsci#301]
I've read in the SAFI_clean.csv per episode 2 and the `key_ID` column in reading in as a `<dbl>` but the lesson says it should be an integer and `<int>`.  I can put in a PR if this should be updated, but I'm not sure if maybe it is just me.

Here are my tidyverse versions, and I'm on R 4.0.3.

── Attaching packages ────────────────────────────────────────── tidyverse 1.3.0 ──
✓ ggplot2 3.3.3     ✓ purrr   0.3.4
✓ tibble  3.0.6     ✓ dplyr   1.0.5
✓ tidyr   1.1.3     ✓ stringr 1.4.0
✓ readr   1.4.0     ✓ forcats 0.5.1

**Comment by atheobold** [comment]
@elliewix -- you are correct. As of the 1.2.0 version of **readr**, the `read_csv()` functions no longer guesses columns are of type integer, instead these columns are guessed as numeric <https://github.com/tidyverse/readr/blob/master/NEWS.md#integer-column-guessing>. This is a minor change, but should be made to update the lesson to the current `read_csv()` behavior!

**Comment by kelseygonzalez** [comment]
Hi @elliewix , would you be interested in submitting a PR for this particular issue?

**Comment by kelseygonzalez** [comment]
We have investigated this a little further and don't find any output in [the lesson](https://datacarpentry.org/r-socialsci/02-starting-with-data/index.html) that shows the `key_ID` is being read and `<int>` and have decided to close the issue. However, if you are able to point us to where exactly this occurs we are open to reopening.
