### ISSUE TITLE
Potential error in Formatting Dates section of Starting with Data

### ISSUE THREAD

**Issue by ayarnell** [datacarpentry/r-socialsci#308]
I think there is a small but confusing error in the episode Starting with Data, Formatting Dates. 
```
char_dates <- c("7/31/2012","8/9/2014",'4/30/2106')
str(char_dates)
as_date(char_dates, format = "%m/%d/%y")
```
Output
`[1] "2020-07-31" "2020-08-09" "2021-04-30"`

The output dates change from the input dates and there is no explanation as to why. There should be a %Y used instead of %y in the last line. That is
`as_date(char_dates, format = "%m/%d/%Y")`

![DateError](https://user-images.githubusercontent.com/35341412/115784848-a7bf1980-a38c-11eb-8e15-e64b989765fc.JPG)

**Comment by juanfung** [comment]
@ayarnell Great catch. Would you be willing to submit a PR to make this change? Maybe also adding an explanation for the `format` argument in `as_date`

**Comment by ayarnell** [comment]
@juanfung Definitely, will do!

**Comment by juanfung** [comment]
Thanks!

**Comment by ayarnell** [comment]
ok PR submitted - hopefully did that right!
