### ISSUE TITLE
logical counting of items/months

### ISSUE THREAD

**Issue by mikerspencer** [datacarpentry/r-socialsci#309]
I had a comment this week, while helping, that the logical steps in the dplyr exercise (e.g. [lines 698-704](https://github.com/datacarpentry/r-socialsci/blob/main/_episodes_rmd/03-dplyr-tidyr.Rmd) ) didn't make much sense.

On working through the problem, I can appreciate the comment. The exercise purpose seems to be teaching wider/longer transforms, but the task is counting observations and wider/longer isn't needed.

e.g. I would solve the task:

```
interviews %>% 
  mutate(items_owned = str_count(items_owned, ";") + 1,
         months_lack_food = str_count(months_lack_food, ";") + 1)
```

But this doesn't include wider/longer transforms.

Perhaps using `pivot_wider` to create a table for a report might be more useful?

**Comment by kelseygonzalez** [comment]
Hi @mikerspencer - this is good feedback. While I wasn't involved with writing this portion of the lesson, I understand your sentiment. I'll bring this to the other maintainers in our next meeting and see if we can develop a plan to address your concern.

**Comment by juanfung** [comment]
@mikerspencer We do appreciate your suggestion, but after discussing decided we will keep the example as is for two reasons:
- While the example as written can be solved in different ways, we do not teach `str_count()`
-  Solving the problem using `pivot_wider()` seems appropriate as the last example [in the docs](https://tidyr.tidyverse.org/reference/pivot_wider.html) is an aggregation (mean not sum, but the idea is the same)
However, if you have any other suggestions to improve this exercise, or the rest of the lesson, please open a new issue and let us know!
