### ISSUE TITLE
Replace JSON episode with Rmarkdown intro

### ISSUE THREAD

**Issue by bbartholdy** [datacarpentry/r-socialsci#311]
I was recently a helper for this workshop, and the [JSON episode](https://datacarpentry.org/r-socialsci/05-json/index.html) seemed like an awkward part of it. I have also never come across the need to process JSON data in my own research, nor do I know anyone else who has (this could of course just be a product of my field of study).

I wanted to suggest an alternative episode, where Rmarkdown is introduced. I think it could be made a seamless extension of the data wrangling and visualisation sections, where the participants could get the opportunity to convert their scripts and plots into a cohesive .Rmd file. I realise this would be a very brief introduction, but I think it would be very useful for the participants to be introduced to some of the possibilities of Rmarkdown (especially in terms of reproducibility). 

Since they already have a script, the episode would consist of very basic markdown syntax (the new markdown features in RStudio will make this less daunting), creating code chunks in a .Rmd file with some accompanying text, and showing how to knit it to .html, .pdf, and .docx.

**Comment by kelseygonzalez** [comment]
Hi @bbartholdy - I think an episode on RMarkdown would be useful and I generally teach it when I teach this workshop. I usually pull on the [Software Carpentry R for Reproducible Scientific Analysis episode on Producing Reports With knitr](http://swcarpentry.github.io/r-novice-gapminder/15-knitr-markdown/index.html) and we could pull on this if we decide to add a lesson. 

I will bring this to my next maintainer's meeting and I will let you know what we decide to pursue.

**Comment by kelseygonzalez** [comment]
@bbartholdy we are super open to making the JSON episode and "extra" episode and adding an .rmardown episode similar to the [Software Carpentry R for Reproducible Scientific Analysis episode on Producing Reports With knitr](http://swcarpentry.github.io/r-novice-gapminder/15-knitr-markdown/index.html). Would you be interesting in taking a first stab at the new episode?

**Comment by bbartholdy** [comment]
@kelseygonzalez sure I'd be happy to take a swing at it! How would you like me to go about it? Replace the 05-json.Rmd with a new RMarkdown episode on my fork?

**Comment by juanfung** [comment]
@bbartholdy If you're interested in contributing an Rmd episode, please add it as a separate episode. We will keep the json episode as an optional episode.

**Comment by jaxgoodlabs** [comment]
@kelseygonzalez I'm just dropping in to second @bbartholdy's comment above. The JSON episode felt like a bit of a non-sequitur to me as well, and I agree that an extended discussion of markdown would be more helpful. 

Another alternative that would flow well from the data visualization material is a short section on regression analysis. Many of the participants we have at Carnegie Mellon will end up using R in the context of a statistics course where linear regression plays a central role. Learning how to use the summary() function to examine the coefficients of a linear regression model is something I think students would get a lot of value from. Using QQ plots and other diagnostic plots to test assumptions of linearity would also be really useful. Some good candidates are presented [here](http://www.sthda.com/english/articles/39-regression-model-diagnostics/161-linear-regression-assumptions-and-diagnostics-in-r-essentials/).

**Comment by bbartholdy** [comment]
I don't think there is enough time in that episode slot to sufficiently cover linear regression. That being said, I definitely agree that there needs to be some linear regression in R in the curriculum for social sciences! Perhaps even a workshop dedicated to introducing generalised linear models.

**Comment by jaxgoodlabs** [comment]
@bbartholdy I may be developing some curriculum along these lines later this summer with Carnegie Mellon Libraries. I'm happy to share it here as a starting point for a devoted episode.

**Comment by bbartholdy** [comment]
That would mainly be for the maintainers @juanfung and @kelseygonzalez. Or maybe something to bring up at a community discussion? I am just coming up with a possible R Markdown replacement for the JSON episode.

**Comment by atheobold** [comment]
@jaxgoodlabs & @bbartholdy -- The Carpentries mission is to build participant's capacity in "essential data and computational skills for conducting efficient, open, and reproducible research." There are substantial differences between *data* skills and *inferential* skills, and the purpose of the Carpentries curricula **is not** to develop researcher's inferential skills. Yes, I would agree that a large number of researchers employ regression methods, but this is beyond the scope of this curriculum and outside of the broader purpose of the Carpentries.

**Comment by bbartholdy** [comment]
@atheobold, @juanfung and @kelseygonzalez, I am getting to a point where I can start testing the episode, but I am having trouble rendering the lesson, and I have no prior experience with Ruby. I get the following error with ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]:

bundle config set --local path .vendor/bundle && bundle install && bundle update && bundle exec jekyll serve
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:50:in `<class:Specification>': undefined method `rubyforge_project=' for class `Gem::Specification' (NameError)
	from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:49:in `<top (required)>'
	from /snap/ruby/212/lib/ruby/3.0.0/rubygems.rb:1348:in `require'
	from /snap/ruby/212/lib/ruby/3.0.0/rubygems.rb:1348:in `<top (required)>'
	from <internal:gem_prelude>:2:in `require'
	from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
make: *** [Makefile:45: serve] Error 1

**Comment by juanfung** [comment]
@bbartholdy I have had problems with Ruby on Mac OS Catalina and never figured out how to fix them. I'm not an expert here. 

My suggestion is to use docker to serve instead: https://github.com/carpentries/lesson-docker

**Comment by bbartholdy** [comment]
Thanks @juanfung , that worked great! Do you know of a good way to make it temporarily publicly available? I will be testing it out in a Data Carpentries workshop next week, and would like to make it available to the participants.

**Comment by juanfung** [comment]
In principle, you should be able to build the site from your fork and have participants visit your fork of the site. In practice, site build is beyond my level of expertise so I can't help much beyond that!

**Comment by bbartholdy** [comment]
@juanfung @kelseygonzalez @atheobold 
I tested the episode at a Data Carpentry workshop last week and received very positive feedback from participants and instructors! I also incorporated some of the feedback into the episode, and I think it is ready for whatever are the next steps.
It can be accessed [here](https://bbartholdy.github.io/r-socialsci/06-rmarkdown/index.html).

**Comment by juanfung** [comment]
Hey @bbartholdy I took a quick look and it looks awesome! We actually have a maintainers meeting on Friday so we can discuss it then, but I think it looks ready to be added.

**Comment by juanfung** [comment]
@bbartholdy When you have a chance, please submit a PR to incorporate this episode into our repo!
