### ISSUE TITLE
Error Opening Project

### ISSUE THREAD

**Issue by StoianAndrei** [datacarpentry/r-socialsci#312]
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:
![Error_Opening_Project](https://user-images.githubusercontent.com/47652458/116796009-45ed7500-ab2d-11eb-8ae0-16ac22c78fb7.png)

Good morning, 

I am trying to do my check-out and as such, I wanted to open the project in RStudio Cloud. Please find the attached photo to see the behavior of creating a new project using git version control. 

Is there something we can do about this issue? 

\- The Carpentries
</details>

**Comment by kelseygonzalez** [comment]
Hi @StoianAndrei ! Did you download this .rproj from this repository? We never intended it to be used by participants or instructors and didn't mean for this file to be available at all, but it snuck in through a recent pull request. I'm going to delete this file now. 

If you have an .rproj file from a different location, please let us know and we'll do what we can to help.
