### ISSUE TITLE
Naming variables in learners' first exercise

### ISSUE THREAD

**Issue by mccowen-ksu** [datacarpentry/r-socialsci#314]
I'm looking here at the <a href = "https://datacarpentry.org/r-socialsci/01-intro-to-r/index.html">Introduction to R</a> episode of the "R for Social Scientists" course.

In the section **Creating Objects with R,** we give students the following warning:

<blockquote>There are some names that cannot be used because they are the names of fundamental objects in R (e.g., if, else, for, see here for a complete list). In general, even if it’s allowed, it’s best to not use them (e.g., c, T, mean, data, df, weights).</blockquote>

A short time later, in the section **Comments,** the concluding exercise asks students to create variables named `length ` and `width` and assign values to them.

The exercise does warn learners that length and width are functions in base R, and how to avoid issues with autocomplete in Rstudio. But it seems like a contradiction that could easily be avoided by suggesting variable names (e.g., `r_length` and `r_width`) that don't correspond to basic functions.

(I'm excited to teach this lesson, and thank you to the authors and maintainers!)

**Comment by juanfung** [comment]
@mccowen-ksu Thank you! Great suggestion. Would you be willing to submit PR for this change?

**Comment by mccowen-ksu** [comment]
> @mccowen-ksu Thank you! Great suggestion. Would you be willing to submit PR for this change?

Yes! I’ll create and submit the PR as soon as possible — likely early next week.
