### ISSUE TITLE
Lesson Contribution - Downloads and Grammar

### ISSUE THREAD

**Issue by Talishask** [datacarpentry/r-socialsci#320]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

I have a suggestion on downloading and saving the data set used for each module. At the beginning of the session, everyone is navigating a new software and the attendees find it difficult to find their file paths. For example, if the instructor has the file saved on the Desktop, some of the attendees have tried using that file path even though theirs is in Downloads.
I think at the beginning of the workshop everyone should download the data set and save it on the Desktop. This way everyone has a uniform file path and there will be less confusion. I find the file names to be unnecessarily lengthy (E.g.: In python module, inflammation-01, inflammation-02) or use of a mix of upper and lower case (E.g.: In R for Social Scientists module, SAFI_clean.csv). In R and Python if the file name is misspelled it generates an error saying the file doesn't exist in the current working directory and this leads to confusion specially to the novice users. Sometimes they do not realize it is the spelling mistake or the missing underscore that lead to this error. Therefore, I think using short file names is important.

I noticed 2 spelling mistakes in the "R for Social Scientists." They are highlighted in red.

Mistake1: This makes **since, since** each item in every row was owned by that household.
https://datacarpentry.org/r-socialsci/03-dplyr-tidyr/index.html

Mistake2: If we try to write our json_data dataframe to a csv as we would **usuall** in a regular dataframe, we will get an error that tells us we have an "unimplemented type 'list' in 'EncodeElement'".
https://datacarpentry.org/r-socialsci/05-json/index.html

**Comment by juanfung** [comment]
@Talishask Thanks! I will fix the typos and discuss the data directory suggestion with the other maintainers at our next meeting tomorrow.

**Comment by juanfung** [comment]
The typos have been fixed #325. We appreciate the suggestion about download paths, but feel using desktop is not good practice. Moreover, there are clear instructions to download the data to the `data` subdirectory for the lesson: https://datacarpentry.org/r-socialsci/00-intro/index.html
