### ISSUE TITLE
Lesson Contribution for Missing Data & Presentation of SAFI Data

### ISSUE THREAD

**Issue by Talishask** [datacarpentry/r-socialsci#321]
I'm a member of The Carpentries Core Team and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

## CONTRIBUTION 1
**Episode**: Introduction to R (https://datacarpentry.org/r-socialsci/01-intro-tor/index.html)
**Section** on "Missing Data"
The example used is rooms <- c(2, 1, 1, NA, 4). So when evaluating
max(rooms, na.rm = TRUE) it can be confusing to a new learner as to why the answer is 4 – since the maximum value in the vector is 4, there are 4 entries and the missing value is at index 4.

So my suggestion is to instead use the example: rooms <- c(2, 1, 1, NA, 7, 3).

## CONTRIBUTION 2
**Episode**: Starting with Data (https://datacarpentry.org/r-socialsci/02-startingwith-data/index.html)
**Section** on “Presentation of SAFI Data”

Before loading the data, it will be helpful to introduce the setwd() function so that there are no issues in locating the data when the learners run the code in the future. It will also help them with their future projects. Introducing this will take 5 minutes maximum. This time can easily be made up during the episode. 

For my teaching demo, I was assigned to teach this episode and when I introduced setwd(), the host and other participants felt that this was very much needed in that episode and suggested that I list this as my contribution for instructor checkout.

See PDF version attached
[instructor-checkout-contributions-UMA-NCCU.pdf](https://github.com/datacarpentry/r-socialsci/files/6503073/instructor-checkout-contributions-UMA-NCCU.pdf)

**Comment by juanfung** [comment]
@Talishask Please let the member know these are great suggestions. I will work on them.

**Comment by atheobold** [comment]
@Talishask -- I really like your idea of more mindfully incorporating file directories into the lesson. I think my preference would be to "go big" and have a section on RStudio projects and the **here** package. These are the tools I use to teach good file management in R, and they take a lot of the icky details about full paths out!

**Comment by kelseygonzalez** [comment]
@atheobold I agree that the here package would be better to introduce than setwd(). We can discuss this further in the upcoming maintainers meeting.

**Comment by juanfung** [comment]
#325 clarifies the example. We appreciate the discussion on `setwd()`, but it is already discussed in ["Before We Start"](https://datacarpentry.org/r-socialsci/00-intro/index.html), which also provides instructions for downloading the data to the appropriate directory. Separately, the maintainers are discussing the possibility of introducing the **here** package in the lesson.
