### ISSUE TITLE
Blank plot in Episode 04 ggplot

### ISSUE THREAD

**Issue by Epsian** [datacarpentry/r-socialsci#35]
First plot (unnamed-chunk-3) is blank.

http://www.datacarpentry.org/r-socialsci/04-Data-visualisation-with-ggplot2/

**Comment by gtlaflair** [comment]
It looks like that is purposeful--to show how layers can be added to a ggplot object

**Comment by Epsian** [comment]
Ah, I get it. Was afraid it was another missing data issue. Feel free to close this.
