### ISSUE TITLE
Typo fix req: "caluculate"

### ISSUE THREAD

**Issue by lalmaraz** [datacarpentry/r-socialsci#352]
Episode "Data Wrangling with dplyr and tidyr" here: [https://datacarpentry.org/r-socialsci/03-dplyr-tidyr/]( https://datacarpentry.org/r-socialsci/03-dplyr-tidyr/ ) has a typo.

The typo is "caluculate", towards the end of the "Applying pivot_wider() to clean our data" section, the sentence "We then group the data by villages and caluculate the mean number of items, so each average is grouped by village.".

Thank you kindly, dear maintainers!

**Comment by juanfung** [comment]
@lalmaraz Thanks!
