### ISSUE TITLE
Lesson 2 formatting is garbled as rendered past `plot(memb_assoc)`

### ISSUE THREAD

**Issue by kerchner** [datacarpentry/r-socialsci#359]
Lesson 2 content below approximately
https://github.com/datacarpentry/r-socialsci/blob/3b07ee727e37d9c9378fdea830ebeea84596d863/_episodes_rmd/02-starting-with-data.Rmd#L515
is garbled. It looks like a syntax error in the markdown may have been introduced.
![image](https://user-images.githubusercontent.com/3451175/136138670-aaa08c6a-e7c0-4df5-80c9-5dea5c937a87.png)

**Comment by juanfung** [comment]
@kerchner Thanks! Fixed.
