### ISSUE TITLE
Introduce alternative to reading csvs with here package in lesson 2

### ISSUE THREAD

**Issue by rachaellam** [datacarpentry/r-socialsci#360]
In lesson 2, "Starting with R," the package `here` is introduced to load a csv. It is written as:

`interviews <- read_csv(here("data", "SAFI_clean.csv"), na = "NULL")`

I would suggest adding the alternative -   `interviews <- read_csv(here("data/SAFI_clean.csv"), na = "NULL")`   - in this lesson because it's used in lesson 5, "Data Visualisation with ggplot2," without any context which might be confusing if this method hasn't been taught yet.

**Comment by LuisaFassi** [comment]
In relation to this issue, I also suggest to explain in more detail setwd() as part of the lesson. At the moment, the lesson mentions "relative paths work regardless of where the associated source file lives inside your project, like analysis projects with data and reports in different subdirectories. This is an important contrast to using setwd(), which depends on the way you order your files on your computer". For a novice, this might seem quite rushed, I suggest providing an example  to better clarify the function setwd() in relation to paths/subdirectories, exploring the pro and cons of using it.

**Comment by juanfung** [comment]
@LuisaFassi thank you, it's a great point and I agree. If you'd like to submit a PR that adds language specifically on `setwd()`, that would be great!
