### ISSUE TITLE
Easier instructions on updating R for Windows

### ISSUE THREAD

**Issue by ezherman** [datacarpentry/r-socialsci#363]
Might be easier for learners using Windows to update R using the `updateR()` function from the `installr` package. Following the [package repo](https://github.com/talgalili/installr), all you need to do is:

`library("installr")`
`updateR()`

I believe this avoids any issues with re-installing packages.

**Comment by juanfung** [comment]
@ezherman Thanks! This is a great suggestion. Is this in reference to the instructor notes, or a suggestion that we address updating? I don't recall if/where we address updates

**Comment by ezherman** [comment]
@juanfung done!
