### ISSUE TITLE
Typo fix request: "the the"

### ISSUE THREAD

**Issue by amycfarrow** [datacarpentry/r-socialsci#365]
Episode [Data Wrangling with dplyr and tidyr](https://datacarpentry.org/r-socialsci/03-dplyr-tidyr/index.html) has a typo in section 'Reshaping with pivot_wider() and pivot_longer()', subsection 'Long and wide data formats'. In the first paragraph of that subsection, it says "it is stated that **the the** key_ID was “added to provide a unique Id for each observation”".

Thank you!

**Comment by juanfung** [comment]
Thanks @amycfarrow !
