### ISSUE TITLE
Inconsistent header usage in Episode 03 dplyr & tidyr

### ISSUE THREAD

**Issue by Epsian** [datacarpentry/r-socialsci#37]
The headers in episode 3 seems inconsistent. Pipes are a double header (## Pipes), while the mutate function is triple (### Mutate), and the summarize function is quadruple (#### The `summarize()` function). Is there a style guide for when to use which headers?

**Comment by juanfung** [comment]
@Epsian I'll work on this now.

@ErinBecker is there a style guide? Otherwise, I'll just default to `###`

**Comment by fmichonneau** [comment]
in general, I use `##` for the first level of headers within the episode. `#` should be for the title of the episode itself.

**Comment by juanfung** [comment]
Thanks @fmichonneau !

**Comment by juanfung** [comment]
Resolved by 9488bbede2361b1f059335657f145264ed043fdb
