### ISSUE TITLE
data.table reference

### ISSUE THREAD

**Issue by alwil** [datacarpentry/r-socialsci#374]
This issue concerns the episode [Data Wrangling with dplyr and tidyr](https://datacarpentry.org/r-socialsci/03-dplyr-tidyr/index.html).

In this episode, I would appreciate a short mention of alternatives to `dplyr` or `tidyverse` more generally. Specifically, `data.table`  is quite a prominent package that is widely used, especially in a context of big data. Many learners might have come across the package or heard of it. 

A short note with [reference to the package page](https://rdatatable.gitlab.io/data.table/) and potentially [comparison between data.table and tidyverse](https://mgimond.github.io/rug_2019_12/Index.html) would be sufficient.

**Comment by juanfung** [comment]
@alwil i like this idea a lot. Would you be interested a PR that adds a brief note `data.table` as an alternative and a link to those sources?

**Comment by juanfung** [comment]
Resolved [linl](www.link.com)
