### ISSUE TITLE
`!` operator mentioned in Episode 03 dplyr & tidyr

### ISSUE THREAD

**Issue by Epsian** [datacarpentry/r-socialsci#38]
The `!` operator is mentioned on line 294, but it may be useful to introduce it earlier, and in a full section rather than a code comment. I propose adding it to Episode 01 R Basics around line 416, where other operators like <, >, ==, and != are introduced. 

http://www.datacarpentry.org/r-socialsci/03-Introducing-dplyr-and-tidyr/
http://www.datacarpentry.org/r-socialsci/01-R-basics/

**Comment by juanfung** [comment]
@Epsian I think this is a good idea. I'm wondering if we should also introduce logical operators when we introduce `!`...

**Comment by juanfung** [comment]
Whoops. Logical operators are introduced in episode 01, shortly after `<,>,==,!=` are introduced.

9831be84fbadeab00e2b8372c979253a1150943a introduces `!` in episode 01.
