### ISSUE TITLE
citation functionality not mentioned

### ISSUE THREAD

**Issue by steltenpower** [datacarpentry/r-socialsci#386]
As datacarpentry is aimed at researchers, citations are an important part of their job.
Therefore a page on Rmarkdown should mention citations.

Maybe just one sentence about it including a link that is a more up-to-date version of
https://www.rstudio.com/blog/rstudio-1-4-preview-citations/

**Comment by atheobold** [comment]
@steltenpower -- I would agree! This could also be a great place to add a short blurb about the `citation()` function in R. Would you be interested in putting in a pull request for this content?

**Comment by ferproanocuenca** [comment]
I have sat in some workshops and find that most instructors use the exercises immediately after introducing a new concept. Other times, the exercises are used later once more information is available to push attendees to interact more or be more involved. So it depends on the teaching style, the lesson's topic, and the time to fit in the schedule. 

Anyhow, I agree it depends on the course and possibly can be moved up in some cases.

**Comment by AvdReis** [comment]
@atheobold -- I have just done the instructor training and would like to contribute to solving this issue as part of my checkout. I would be interested in putting in a PR for this.

**Comment by juanfung** [comment]
@AvdReis that would be great! i don't have any insight into this, so please use your judgement
