### ISSUE TITLE
No_listed_items to be excluded when calculating the row sum

### ISSUE THREAD

**Issue by jing-library** [datacarpentry/r-socialsci#387]
for the code

mutate(number_items = rowSums(select(., bicycle:car))) 

in the chapter [03-dplyr-tidyr.Rmd](https://github.com/datacarpentry/r-socialsci/blob/main/_episodes_rmd/03-dplyr-tidyr.Rmd), families that do not have any items are assigned 1 in the variable number_items. The column "no_listed_items" should be excluded when calculating the row sum. 
mutate(number_items = rowSums(select(., bicycle:car, -no_listed_items)))

**Comment by atheobold** [comment]
@jing-library -- Great note! This would be a great modification to the lesson. Would you be interested in putting in a PR for this change? If so, could you also insert a sentence surrounding the code explaining *why* we are "unselecting" the `no_listed_items` column?

Thanks!
