### ISSUE TITLE
errors in the pivot_longer() section of  r-socialsci/_episodes_rmd/03-dplyr-tidyr.Rmd 

### ISSUE THREAD

**Issue by jlahne** [datacarpentry/r-socialsci#395]
The pivot_longer() demo starting at line 695 in [03-dplyr-tidyr.Rmd](https://github.com/datacarpentry/r-socialsci/blob/main/_episodes_rmd/03-dplyr-tidyr.Rmd) is incorrect because of the use of the `:` selector in the `cols = ` argument.  The `interviews_wide` data frame created in the example before, used for this part of the demo, can have a different order of columns than that implied by the `burntbricks:sunbricks` selector.  

I would suggest fixing this by explicitly specifying columns to select for pivoting, e.g.

```
interviews_wide %>%
  pivot_longer(cols = c("muddaub", "cement", "sunbricks", "burntbricks"),
               names_to = "respondent_wall_type",
               values_to = "wall_type_logical")
```

While this is longer it also is not order-dependent and will not fail if columns are moved/reordered.

The issue must have arisen earlier, because the number of rows in `interviews_long` is given incorrectly in line 705, which counts rows in the `interviews_long` tibble: `nrow(interviews_long)`.  In the knitted file this computes 262 rows for `interviews_long`, but if it should be 4 times as long as `interviews`, it should be `4 * 131 = 524` rows.

**Comment by juanfung** [comment]
@jlahne thanks and great catch. Would you be interested in submitting a PR with this change?

**Comment by juanfung** [comment]
@jlahne no problem! I will take care of it in the next few days, using exactly the code you suggest above. You are always welcome to contribute in the future!

**Comment by elifdy** [comment]
@juanfung I submitted a PR with this change.
