### ISSUE TITLE
A lower alpha helps visualizing transparency of overlapping points in the scatterplot

### ISSUE THREAD

**Issue by carlosramre** [datacarpentry/r-socialsci#407]
When introducing "alpha" in the Data Visualizations with ggplot2 episode, I'd suggest changing it to alpha = 0.3, instead of the current alpha = 0.5. When following this lesson, the changes observed with alpha = 0.5 are barely perceptible by me, and I suspect to others, but a lower alpha helped me perceive the modified transparency of overlapping observations. 

interviews_plotting %>%
    ggplot(aes(x = no_membrs, y = number_items)) +
    geom_point(alpha = 0.3)

**Comment by juanfung** [comment]
@carlosramre i think this is a good suggestion, thank you! would you be willing to submit a PR with these changes?

**Comment by carlosramre** [comment]
Sure, I think I just did that.

**Comment by juanfung** [comment]
thank you @carlosramre !
