### ISSUE TITLE
Visual learning aid for tidy data

### ISSUE THREAD

**Issue by isaac-jennings** [datacarpentry/r-socialsci#426]
Hi, 

As a requirement for instructor training checkout, I am hoping this contribution is suitable and meaningful for the community and future learners. 

In episode five 'Data wrangling with tidyr',  the explanation of the three rules governing tidy data [https://datacarpentry.org/r-socialsci/04-tidyr/index.html#reshaping-with-pivot_wider-and-pivot_longer](url) does not contain any material that caters for visual learners.  At present, the concept of tidy data is presented in a format most suitable for learners who have a strengths in processing information that is written. 

Is there scope to consider adding a visual graphic that depicts the tidy data concept? Wickham and Grolemund 2015 have a suitable graphic in their publication R for Data Science: [https://d33wubrfki0l68.cloudfront.net/6f1ddb544fc5c69a2478e444ab8112fb0eea23f8/91adc/images/tidy-1.png](url)

This does not necessarily add any additional information for an instructor to communicate to learners. Rather it would act as a instructional aid to communicate an important concept to people with preferences for visual styles of learning.

Kind regards,

Isaac

**Comment by juanfung** [comment]
@isaac-jennings yes, agreed that a visualization would be very helpful! if the graphic you link can be used with appropriate attribution, i would love to see this added (though note that the link is not working for me). 

would you be interested in a PR to incorporate this visual?

**Comment by isaac-jennings** [comment]
Hi @juanfung,

Apologies for uploading a faulty link. If you get a chance, the image I had in mind was Fig 12.1 on the following page: https://r4ds.had.co.nz/tidy-data.html

Happy to do a PR. However, I will first double check the copyright and attribution requirements (if any) before submitting.

**Comment by juanfung** [comment]
@isaac-jennings thanks! Fig 12.1 or something similar would be a great addition. Will be on hold for a PR 🤞
