### ISSUE TITLE
Mention other packages for creating tables

### ISSUE THREAD

**Issue by amannj** [datacarpentry/r-socialsci#438]
In section [Insert tables](https://datacarpentry.org/r-socialsci/06-rmarkdown/index.html#insert-table), it would be helpful to mention [other packages for creating tables](https://bookdown.org/yihui/rmarkdown-cookbook/table-other.html).

It would be constructive to summarise some of their key features, such as different output formats, formatting and visualisation options or interactive options.

**Comment by juanfung** [comment]
@amannj thank you this is a great idea. would you be willing to submit a PR with similar content to the link? 

actually rather than a bullet list, a table might be nice...

**Comment by juanfung** [comment]
@amannj thank you!
