### ISSUE TITLE
change in dplyr 1.1.0

### ISSUE THREAD

**Issue by mometRie** [datacarpentry/r-socialsci#439]
Hey all! 

I would like to note that there is an important change made in the new version of dplyr 1.1.0 package that might cause some issues! 
In the case when group_by is used with more than one variable, you need to use a different function: refine() 

see in https://www.tidyverse.org/blog/2022/11/dplyr-1-1-0-is-coming-soon/

It might be that many of us have missed this new feature and i think it is important to let our students know this, during the lessons.

https://github.com/datacarpentry/r-socialsci/blob/d130e887245e995e467620b1c335d67c2358ab5a/episodes/03-dplyr.Rmd#L362

**Comment by jessesadler** [comment]
Thanks for bringing this issue up. However, I do not think that this is a problem in this case. The new function `reframe()` is introduced in `dplyr 1.1.0` for when you want to perform multiple summaries per group. In the provided example on line 362 only one row is produced per group of "village" and "memb_assoc". Therefore, we can continue to use `summarise()`.
