### ISSUE TITLE
Managing conflicts

### ISSUE THREAD

**Issue by FS94** [datacarpentry/r-socialsci#445]
I would like to suggest that a brief mention to **conflicts** should be added at, possibly, the "02-starting-with-data" episode.

When introducing the _tidyverse_ package, it would be an ideal opportunity to introduce the notion of conflicts and alert the learner to possible issues these conflicted functions can create. This is particularly relevant since loading _dplyr_ automatically creates two conflicts with preloaded R functions (`filter` and `lag`). 

Recent _tidyverse_ package versions already suggest/mention this automatically when loaded, but I believe a brief introduction on what conflicts are, how they could be found (`conflicted::conflict_scout()`) and how they can be managed (e.g., `conflicted::conflict_prefer("function", "package_preferred”`), would prove useful.

**Comment by eirini-zormpa** [comment]
HI @FS94, that's an excellent suggestion 🚀 ✨ Would you be up for adding a couple of sentences explaining what you just listed and submitting a pull request? Please let me know if you'd like any support with doing that!

**Comment by FS94** [comment]
Sure. I'll do it in the next few days. I may need some guidance, but I'll be sure to let you know. Thanks.
