### ISSUE TITLE
Cleaner SAFI_clean dataset

### ISSUE THREAD

**Issue by ndporter** [datacarpentry/r-socialsci#446]
The `SAFI_clean.csv` dataset currently linked from [Setup](https://datacarpentry.org/r-socialsci/index.html#setup-instructions) and originally from [figshare](https://figshare.com/articles/dataset/SAFI_Survey_Results/6262019) has multiple small errors in the first few rows. 

Specifically: 

- the second `key_ID` is `1` when it should be `2` according to the pattern of every other row
- there are initial spaces in the respondent_wall_type column that produce non-obvious differences when using

Neither of these substantively affects this lesson that I could find, although the inspection output in [episode 2](https://datacarpentry.org/r-socialsci/02-starting-with-data.html#presentation-of-the-safi-data) does clearly show the erroneous key_ID.

But given that the standard DC:SS workshop goes through cleaning data and then working in R with ostensibly clean data, it would be ideal to have a dataset that doesn't have readily visible typos.

**Comment by jessesadler** [comment]
@ndporter I agree with your point about making these minor changes to the data. Should we just make the changes to the `SAFI_clean.csv` file and then link to download the file from our GitHub repository as is done with the JSON file? We can then say that the data originates from figshare. It does not seem clear to me that changing it on figshare is the thing to do.

I will also note that the link to the JSON file does not work, so this should also be changed. I can go ahead and make these changes if we agree this is the way to go about them.

**Comment by ndporter** [comment]
@jessesadler makes sense to me, but I realize that changes to the dataset should be at least run by the [curriciulum advisory committee](https://docs.carpentries.org/topic_folders/lesson_development/cac-consult-rubric.html). I'm on the CAC, so I'll put something on our Slack and if we need to talk more, I'll add it to the agenda for our June meeting then follow up.

That said, you can make changes to fix the JSON link now, since it's not substantive changes - just a repair to the link.

**Comment by juanfung** [comment]
@ndporter perfect! @eirini-zormpa is a maintainer for this lesson and also on CAC! keep us posted

**Comment by ndporter** [comment]
The CAC approved both the suggested changes and (related) hosting a version of the dataset locally rather than linking to figshare. Thanks!

**Comment by juanfung** [comment]
@ndporter that's great! would you be interested in submitting the changes?

**Comment by ndporter** [comment]
@juanfung  I don't have the bandwidth for that. I'm just reporting back from the CAC. Sorry!
