### ISSUE TITLE
Loading SPSS version of data assumes RStudio

### ISSUE THREAD

**Issue by juanfung** [datacarpentry/r-socialsci#45]
The first exercise in episode 02 asks the student to load `"data/SN7577_spss.sav"` using the RStudio import wizard. 

Would it be worthwhile to show how to load such datasets *without* using RStudio's import wizard? For example `foreign::read.spss` or `haven::read_spss`. The latter is included as part of the `tidyverse`.

**Comment by fmichonneau** [comment]
the SPSS file has been removed from the lesson
