### ISSUE TITLE
Connecting to the RStudio GUI

### ISSUE THREAD

**Issue by drjohnrussell** [datacarpentry/r-socialsci#453]
I am wondering if others have considered how to attach some of the elements within the workshop to the RStudio GUI explicitly - I think, for instance, about an exercise where new functions are called using the ? button in the console, and where you can see those in the lower right window of RStudio. Also, how, instead of writing "view()", you can click on the database in your environment.

I understand the desire to not lean too much into this (especially for things like importing using a script/console instead of the File -> Import Dataset feature because it removes reproducibility), but understanding how RStudio can hold your hand for certain features, and then write it out in the console, is a big part of making the learning curve less steep, right?

**Comment by juanfung** [comment]
@drjohnrussell it's a valid point. I am hesitant to add "screenshot" style graphics to accompany the lesson, for several reasons: they are difficult to maintain as RStudio evolves; not everyone is an RStudio user; it's difficult to draw the line on how many graphics to include and for what parts of the lesson. 

I definitely agree that the lesson could use more visual aids, but I would favor less specific graphics and more generic infographics or visualizations. I will let the other maintainers weigh in (@ErinBecker @jessesadler) and also note that such changes would have to be discussed more broadly than our lesson, as then the question is why other lessons are not doing the same.

**Comment by juanfung** [comment]
closing as not critical. instructors may have rstudio open to showcase this without having to add to lesson
