### ISSUE TITLE
the "IMPORTANT NOTE" callout obscures code boxes in some lessons (example: Lesson 6: R Markdown)

### ISSUE THREAD

**Issue by jlahne** [datacarpentry/r-socialsci#460]
It seems like the new callout (IMPORTANT NOTE) format is interfering with the content of some code chunks.  In [line 231](https://github.com/datacarpentry/r-socialsci/blob/076763e1509d1594af77f451e76a55509e3ebf28/episodes/06-rmarkdown.Rmd#LL233C33-L233C33) of Episode 6 (R Markdown) there should be a setup chunk that pulls in the SAFI_clean.csv file, but in both Firefox and Safari it is obscured in the code chunk, regardless of window size (screenshot attached).

<img width="2560" alt="Screenshot 2023-05-15 at 1 19 54 PM" src="https://github.com/datacarpentry/r-socialsci/assets/48262718/39967839-a710-4c28-a1c7-bc53ec846448">

I can't figure out how to fix this (hence no pull request), as it has to do with the HTML/CSS template.

**Comment by juanfung** [comment]
@jlahne thanks for bringing this up. i think it's beyond this lesson's scope but definitely worth addressing

you might submit an issue to [Workbench](https://github.com/carpentries/workbench) or [sandpaper](https://github.com/carpentries/sandpaper), not sure which (maybe both?)

**Comment by jlahne** [comment]
Will do, after a quick review it seems like it should go to the sandpaper repo...
