### ISSUE TITLE
Replace superseded separate_rows() function

### ISSUE THREAD

**Issue by ndporter** [datacarpentry/r-socialsci#462]
Per the tidyr documentation, the `separate_rows()` "function has been superseded in favour of `separate_longer_delim()`". Going forward, the [tidyr episode](https://datacarpentry.org/r-socialsci/04-tidyr.html#applying-pivot_wider-to-clean-our-data) should be updated eventually to reflect the function that receives continued support.

Current code will not break, but the function is no longer being actively developed.

**Comment by juanfung** [comment]
@ndporter thanks! would you be willing to submit a PR?

**Comment by ndporter** [comment]
I'm glad to submit one, but won't have a chance for a while and am likely to forget by then (thus why I put an issue). Feel free to @ me if there's no PR in a couple of weeks.

**Comment by juanfung** [comment]
@ndporter just checking in if you would still be able to submit a PR for this update?
