### ISSUE TITLE
Recommended updates to handouts

### ISSUE THREAD

**Issue by ndporter** [datacarpentry/r-socialsci#464]
Looking at the code reference handouts ([example](https://datacarpentry.org/r-socialsci/instructor/intro-R-handout.html)), I have a few suggestions to improve their usefulness and utilization:

1. Add a note on the handouts to the [Instructor Notes](https://datacarpentry.org/r-socialsci/instructor/instructor-notes.html) main section so people know about them. Be sure to briefly explain what they are and how they should be used
2. Likewise, consider adding inline instructor notes either on the pages they refer to (as an extra resource) and/or pages that rely/build on those lessons (as a "getting up to speed" help)
3. Standardize how you deal with the penguins data and with libraries. Right now, [Starting with Data](https://datacarpentry.org/r-socialsci/instructor/starting-with-data-handout.html) assumes you have the data downloaded locally in a `data` subdirectory but includes other `library()` calls, [Data Wrangling](https://datacarpentry.org/r-socialsci/instructor/data-wrangling-handout.html) loads the penguins data from a library, and [data visualization](https://datacarpentry.org/r-socialsci/instructor/data-visualisation-handout.html) assumes you already have both the data and libraries loaded into memory. My suggestion here is to explicitly include all libraries and the data imports in each handout so that it doesn't matter if you do them sequentially or individually.
4. Modify or remove the paragraph at the start of Data Wrangling and Data Visualization that reads "This document contains all of the functions that we have covered thus far in the course. It will be updated every week, after we’ve added new skills. Each function is presented alongside an example of how it is used." The updated weekly clause is confusing and probably unhelpful. The rest is also unclear, particularly since each handout has only that section and is not cumulative.
5. Consider restructuring this so all the code handouts are on a single page, but in sections. Sections are still linkable, and this would make it easier for learners to see how things are structured. If this is not possible or preferred, it would at least be helpful to rename the handouts with numbers so they appear in order in the menu (e.g. `Code Handout 1`...).

**Comment by juanfung** [comment]
@ndporter thank you, these are good suggestions. Would you be willing to submit a PR to make the suggested changes?

**Comment by juanfung** [comment]
Per discussion with @eirini-zormpa and @jessesadler, considering removing altogether to facilitate long-term maintenance of lesson. Material is not altogether necessary given existing resources outside of lesson as well as continuous improvements/changes to packages and associated functions

**Comment by jessesadler** [comment]
Closed with #489
