### ISSUE TITLE
Adding some information to the Before we start episode (R for Social Scientists)

### ISSUE THREAD

**Issue by Konstantinna** [datacarpentry/r-socialsci#467]
Suggestions:
1. **What is R studio section** https://datacarpentry.org/r-socialsci/00-intro.html#what-is-r-what-is-rstudio
- Adding a brief description of how RStudio can be used as a presentation tool: a handy option many beginner users don't realise is available.
- Suggested text:
You can also use the R Presentations feature to present your work in an HTML5 presentation mixing Markdown and R code. You can display these within R Studio or your browser. There are many options for customising your presentation slides, including an option for showing LaTeX equations. This can help you share your work with colleagues and collaborators and also has an application in teaching and classroom use.

2.  **Why learn R** https://datacarpentry.org/r-socialsci/00-intro.html#why-learn-r
- Adding a few sentences to the paragraph **R code is great for reproducibility** on packages that help you ensure dependency management and a reproducible snapshot that lets you “save” and “load” the state of your project library. 
- Suggested text:
To further support reproducibility and transparency, there are also packages that help you with dependency management: keeping track of which packages we are loading and how they depend on the package version you are using. This helps you make sure existing workflows work consistently and continue doing what they did before. Packages like renv let you “save” and “load” the state of your project library, also keeping track of the package version you use and the source it can be retrieved from.

**Comment by juanfung** [comment]
@Konstantinna these are great suggestions to improve the lesson. would you be interested in submitting a pull request?

**Comment by Konstantinna** [comment]
@juanfung Thank you. I submitted one: let me know if you can see it

**Comment by Konstantinna** [comment]
Feel free to edit out if I messed anything up :D https://github.com/datacarpentry/r-socialsci/compare/main...Konstantinna:r-socialsci:Konstantinna-patch-1

**Comment by ndporter** [comment]
It looks like you made changes on your local fork but never added a Pull Request so the main repository knew you wanted to push it here, so I created the pull request (#472 ). Thanks @Konstantinna !
