### ISSUE TITLE
About pivot_wider/longer functions

### ISSUE THREAD

**Issue by msquiroga89** [datacarpentry/r-socialsci#470]
Hi!

I would like to raise a question about the way `pivot_wider` and `pivot_longer` are presented in the R for Social Sciences lesson. It can be a very challenging set of functions, but the fact that we first have to separate rows and create logical variables can be a distracting moment for learners. The transformation needed is difficult, and maybe it’s not easily understandable why we need to do that.

We talked about it in the CAC, and since there seem to be [other aspects of the dataset to be discussed](https://github.com/datacarpentry/socialsci-workshop/issues/49), we thought that it could be a good opportunity to include a different approach to these functions, like chosing variables that don't need a previous transformation.

Thanks!

**Comment by juanfung** [comment]
@msquiroga89 thank you that's great feedback! would you be interested in submitting a PR or providing some suggestions to improve the illustration of the two functions?

**Comment by juanfung** [comment]
Per discussion with @eirini-zormpa perhaps make this section optional, in addition to improving the example

**Comment by bbartholdy** [comment]
@juanfung sure! I'll see what I can come up with. On this branch <https://github.com/bbartholdy/r-socialsci/tree/tidyr-adjust> (for anyone interested).

**Comment by msquiroga89** [comment]
Hi, sorry I disappeared, I got caught up in my work. I would like to collaborate with this section of the lesson, are you developing an alternative?

**Comment by juanfung** [comment]
@bbartholdy @msquiroga89 just checking in on this issue...let us (maintainers) know if you need any help!

**Comment by juanfung** [comment]
@bbartholdy no worries, that sounds good and your contributions are much appreciated!

**Comment by bbartholdy** [comment]
I have reorganised the episode as discussed above. I had to deviate a bit from the original plan in order for the episode to make sense (https://github.com/bbartholdy/r-socialsci/commit/a9182ce28dc694d3c31236913647941f83c10066).

To summarise:
- The transformation of `respondent_wall_type` has been removed
- There is, instead, a step-by-step guide to transform `items_owned`
- The transformed `items_owned` data frame is used to demonstrate `pivot_longer`
- Exercises now involve creating summary tables from the longer data frame (to demonstrate how it differs from the wider format)
- Creating `interviews_plotting` is now directly integrated in the episode (before it seemed more like an afterthought)

Still needed:
- The figures showing the reshaping of `respondent_wall_type` need to be updated to depict `items_owned`
- an optional exercise at the end could be going back to the original data frame. This would involve introducing `reframe()`

I wanted to get some input on the new layout before changing the figures (@juanfung , @msquiroga89 ?).

**Comment by juanfung** [comment]
@bbartholdy thank you for the incredible amount of work you've done on this! apologies for not replying sooner, but i finally had a chance to serve your changes locally and have two comments:

- this is a fantastic new layout and i support modifying the accompanying figures
- when i serve locally, i am getting the following error:
> Error in separate_longer_delim(., items_owned, delim = ";"): could not find function "separate_longer_delim"

i checked and i have tidyr 1.3.0 installed, so i'm puzzled. i'm not well versed in how workbench works, and whether there is a local environment enforcing package versions (but if there were, i wouldn't be getting an error). just flagging to make sure you double check this all works as intended. i am guessing it's a local problem on my end, but can't figure it out

**Comment by bbartholdy** [comment]
It sounds like a local problem, I didn't have any issues, including on a fresh Ubuntu install. I know there were problems with some previous versions of {renv}, so maybe worth updating? It might also be an issue with the way the workbench uses {renv}, but I also don't really know enough about it.
