### ISSUE TITLE
Confusing library installation instructions

### ISSUE THREAD

**Issue by fordfishman** [datacarpentry/r-socialsci#478]
There are a few inconsistencies in the setup for this lesson. In Summary and Setup, there are some brief instructions for saying to install `tidyverse` and `here`. The first episode Before We Start has more detailed instructions and information about installing libraries in general. However, Before We Start only specifically speaks about installing `tidyverse` and not `here`. Given that a lot of participants will have trouble installing libraries before the session, that means that at Before We Start, they will likely not have either installed, and will be installing live at the workshop (which is what happened when I ran this workshop with a colleague). 

I would recommend adding some text about installing `here` in Before We Start.

**Comment by juanfung** [comment]
@fordfishman agreed. this is largely a result of the piecemeal development of the lesson. 

Would you be interested in submitting a PR to address the inconsistencies?

**Comment by fordfishman** [comment]
Sure, I'll submit a PR where I add in installing `here` into Before We Start.

**Comment by fordfishman** [comment]
A little confused about which branch to use for the PR. Should I be doing a PR off my own custom branch to `main` or to `gh-pages` as suggested [here](https://github.com/datacarpentry/r-socialsci/blob/main/CONTRIBUTING.md)? I see that PRs in the past have been merged to `main`.

**Comment by zkamvar** [comment]
Mea culpa. That contributing is out of date. The updated version is here: https://github.com/zkamvar/r-socialsci/blob/zkamvar-patch-1/CONTRIBUTING.md (and is currently a PR in #480)
