### ISSUE TITLE
Tweak data output in episode 2 

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/r-socialsci#48]
Currently, many datasets are shown in their entirety and it's distracting, we need to use `head()`, or adjust `options()` to limit the size of the outputs.

**Comment by juanfung** [comment]
So, I created a branch to fix this but somehow made the changes on `gh-pages` and pushed with this commit 09fc7e0ce6f066f347ce8cb4c3462a4dbb4b3f92. This commit 80e2d154e158c3bb5fa272672bc41e53a1461c23 pushes rendered pages.

**Comment by fmichonneau** [comment]
with the switch to the SAFI dataset, this is addressed.
