### ISSUE TITLE
Broken link to dataset description

### ISSUE THREAD

**Issue by jcoliver** [datacarpentry/r-socialsci#490]
### What is the problem?

On the page for episode 2 (https://datacarpentry.org/r-socialsci/02-starting-with-data.html), in the [Presentation of the SAFI Data](https://datacarpentry.org/r-socialsci/02-starting-with-data.html#presentation-of-the-safi-data) section, there is a hyperlinked "dataset description" that directs to https://www.datacarpentry.org/socialsci-workshop/data/, but that URL resolves as a Page not found. I'm not sure where it _should_ direct to now, but perhaps https://datacarpentry.org/socialsci-workshop/index.html#data is an option?

### Location of problem (optional)

https://datacarpentry.org/r-socialsci/02-starting-with-data.html#presentation-of-the-safi-data

**Comment by juanfung** [comment]
@jcoliver good catch! i think linking to that page makes sense, would you be willing to submit a PR to fix the link?

**Comment by marionwalton** [comment]
This might be the missing page with the dataset description? https://datacarpentry.org/socialsci-workshop/data.html
Looks like the URL just lost a "www"
