### ISSUE TITLE
Fix typos in text and improve clarity 

### ISSUE THREAD

**Issue by marionwalton** [datacarpentry/r-socialsci#495]
### What is the problem?

On the page for episode 2 (https://datacarpentry.org/r-socialsci/02-starting-with-data.html), in the [Renaming factors](https://datacarpentry.org/r-socialsci/02-starting-with-data.html#renaming-factors) section, the paragraph about respondents with missing data isn't clear. )
The lack of clarity is mainly caused by two typos (sentences are missing parts of verbs - "is" and "be") 
The meaning is also somewhat muddied because we usually use "who" to refer to people (not "which"):
> "there are some respondents for which the information about whether they were part of an irrigation association hasn’t been recorded, and encoded as missing data. They do not appear on the plot. Let’s encode them differently so they can counted and visualized in our plot."

I'd suggest the following replacement (changes are bolded): 

> "there are some respondents for **whom** the information about whether they were part of an irrigation association hasn’t been recorded, and **is** encoded as missing data. **These respondents** do not appear on the plot. Let’s encode them differently so they can **be** counted and visualized in our plot."

### Location of problem (optional)

https://datacarpentry.org/r-socialsci/02-starting-with-data.html

**Comment by juanfung** [comment]
@marionwalton great catch! are you able to submit a PR with those changes?
