### ISSUE TITLE
add output cells

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/r-socialsci#5]
For each input chunk of code, show the output that will be produced. This will help the learners and the instructors to know that they are getting the expected output. 

Output code should be marked with `.output:` as described [here](http://swcarpentry.github.io/lesson-example/04-formatting/index.html). 

See also https://github.com/datacarpentry/python-socialsci/issues/11

**Comment by ErinBecker** [comment]
Partially addressed by https://github.com/datacarpentry/r-socialsci/pull/14/

**Comment by ErinBecker** [comment]
- [ ] episode 00 
 - [ ] episode 01 
 - [ ] episode 02 
 - [ ] episode 03 
 - [ ] episode 04 
 - [ ] episode 05 
 - [ ] episode 06

**Comment by ha0ye** [comment]
Episode 02 has some code that generates a large amount of output:
```
dim(SN7577_csv)        # no of rows and columns
nrow(SN7577_csv)       # number of rows
ncol(SN7577_csv)       # number of columns

head(SN7577_csv)       # shows first 6 rows (but truncates the variables)
tail(SN7577_csv)       # shows last 6 rows (but truncates the variables)

names(SN7577_csv)      # lists all of the column names
names(SN7577_spss)     # Despite the extra text in the 'View' the column names for the spss variable 
                       # are the same as the csv version
rownames(SN7577_csv)   # list the column names, esentialy index numbers which we don't really need

str(SN7577_csv)        # Show the overall structure of the variable, similar byt more complex to what
                       # what we have seen for other variables.
summary(SN7577_csv)    # displays summary statistics for the different columns.
```

Do we want to include the output for all of this?

**Comment by fmichonneau** [comment]
this has been addressed
