### ISSUE TITLE
dplyr/tidyr episode should be rewritten to use the SAFI dataset

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/r-socialsci#50]
the same dataset should be used across lessons and episodes in Data Carpentry workshops.

**Comment by juanfung** [comment]
@fmichonneau episode  2 also uses *both* the SAFI and the SN7577 data sets. 

Episode 1 states, at the beginning, that "In this lesson we we be using 3 data files": SAFI_results.csv, SN7577.csv, and SN7577.tab.

Does the whole lesson need to be re-written?

**Comment by fmichonneau** [comment]
this has been addressed by Erin's rewrite of the lesson.
