### ISSUE TITLE
Tidyverse/Lubridate automatically loaded alongside other packages

### ISSUE THREAD

**Issue by AndrzejRomaniuk** [datacarpentry/r-socialsci#501]
### What is the problem?

A minor issue in the "Formatting Dates" subsection of 02:
"We are going to use the package lubridate, which is included in the tidyverse installation but not loaded by default, so we have to load it explicitly with [library(lubridate)](https://lubridate.tidyverse.org/)."

In the newer Tidyverse iterations it is loaded by default, perhaps it is good to take this into consideration, e.g.

"We are going to use the package lubridate, which is included in the tidyverse installation and should be loaded by default. However, if we deal with other installation of tidyverse, we can manually load it by typing [library(lubridate)](https://lubridate.tidyverse.org/)."

### Location of problem (optional)

https://datacarpentry.org/r-socialsci/02-starting-with-data.html#formatting-dates

**Comment by juanfung** [comment]
@AndrzejRomaniuk thank you for opening this issue, great catch. That sounds like a good fix to me. Would you be willing to submit a pull request with the suggested change?

**Comment by AndrzejRomaniuk** [comment]
Once am home today I will do it :)

**Comment by AndrzejRomaniuk** [comment]
#502
