### ISSUE TITLE
database episode 

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/r-socialsci#51]
- [ ] fix formatting issues
- [x] put database file in a `data/` folder to follow good practices of working directory organization mentioned in first episode

**Comment by cwant** [comment]
Also, that episode has errors everywhere in the rendered content:

http://www.datacarpentry.org/r-socialsci/06-Using-relational-database-with-R/

**Comment by sechilds** [comment]
Looking into these errors, it looks like the SQLite database SN7577.sqlite is an empty file -- so when the `.Rmd` files generate the episode Markdown file, it generates the errors.

**Comment by cwant** [comment]
When I started to look at this module, I had to grab the database from here:

http://www.datacarpentry.org/sql-socialsci/data/SN7577.sqlite

**Comment by sechilds** [comment]
Yeah - that needs to be added to this repo.

**Comment by juanfung** [comment]
Second task resolved by 9067b8094bfb4be2f5c7fa9cfc67f62d432d88ea

**Comment by fmichonneau** [comment]
in preparation for the initial release of this lesson, the database episode has been removed. It can re-integrated once the SQL lesson for this curriculum has been revamped.

**Comment by kelseygonzalez** [comment]
Status update: This will be reviewed once the database episode is brought back in, pending official release of the DC Social Science SQL lesson.

**Comment by juanfung** [comment]
Closing until database episode is revived
