### ISSUE TITLE
Demonstrating the contrast between ggplot2 and baseR plotting

### ISSUE THREAD

**Issue by noman32** [datacarpentry/r-socialsci#515]
### How could the content be improved?

As this course is designed for anyone who does not necessarily have any previous exposure to R, I think showing a couple of examples of creating plots using baseR plot functions is useful. From my experience of training R to professionals, I found it quite motivating for the learners atleast to know that we can create plots and even add further layers on an existing plot using base R commands like plot(), abline() etc. However for better visualization, ggplot2 is certainly a good choice. In that way, learners can appreciate ggplot2. 
In addition, learners (specially the new comers in R/programming) come to know that for quick plotting for eg EDA, we can simply use base R commands, without loading any additional library. We can either add couple of examples at the beginning of the ggplot episode or alternatively, at the end of ggplot episode, once they master the ggplot skills.
Just to share, in my trainings i show the learners very few examples from base R, lattice, qqplot (sharing with them some official documentation links for further exploration, if they like) and then go to ggplot in full swing. By this learners come to know there are multiple ways for visualization.

**Comment by juanfung** [comment]
@noman32 you are absolutely right. over time, the lesson has evolved in ways that are not necessarily optimal as a whole.

since you have some experience teaching minimal base plotting before ggplot, would you be interested in submitting a PR with this change?

**Comment by juanfung** [comment]
@noman32 no worries if you're unable but wanted to double check

**Comment by noman32** [comment]
Hi Juan,Thanks for your email. I have already forked a branch from the main. Still trying to figure out how to contribute. Will sit again in this weekend :)RegardsNoman

    On Wednesday, September 4, 2024 at 04:14:12 PM GMT+1, Juan Fung ***@***.***> wrote:  
 
 


@noman32 no worries if you're unable but wanted to double check

**Comment by noman32** [comment]
Hi Juan,Just to let you know that I have made some changes in the 05-ggplot2.Rmd file and merged the pull request. Could you please have a look and let me know the way forward. To share, this is my first time ever incorporating any changes in github repository. Please let me know if I made any mistakes. Thanks in advance for your support.RegardsNoman 

    On Wednesday, September 4, 2024 at 09:07:31 PM GMT+1, Noman H Chowdhury ***@***.***> wrote:  
 
  Hi Juan,Thanks for your email. I have already forked a branch from the main. Still trying to figure out how to contribute. Will sit again in this weekend :)RegardsNoman

    On Wednesday, September 4, 2024 at 04:14:12 PM GMT+1, Juan Fung ***@***.***> wrote:  
 
 


@noman32 no worries if you're unable but wanted to double check

**Comment by juanfung** [comment]
@noman32 thank you so much! i will take a look at your repo and circle back.

**Comment by noman32** [comment]
Hi Juan, Thanks for your msg. Glad to know that you liked the addition!I see this msg in my github:

Does it mean that there is nothing left in my end?
RegardsNoman

    On Wednesday, October 9, 2024 at 08:57:57 PM GMT+1, Juan Fung ***@***.***> wrote:  
 
 


@noman32 thank you for your patience. i finally had a chance to review your pull request and i think it's a perfect addition! it's brief and provides awareness of options outside of ggplot2, and i liked the addition of qplot.

i think the next step is to open a pull request from your fork main branch to our main branch. let me know if you have any questions!

**Comment by juanfung** [comment]
@noman32 i opened a PR but note there are some conflicts: https://github.com/datacarpentry/r-socialsci/pull/532

you can try resolving them, if you feel comfortable, or we (maintainers) can take care of it.

**Comment by noman32** [comment]
Hi Juan, I am not sure how to resolve this. Could you guys please take care of this. Would really appreciate this.Happy to contribute in any other ventures.Thanks 
Noman

    On Thursday, October 10, 2024 at 03:42:02 PM GMT+1, Juan Fung ***@***.***> wrote:  
 
 


@noman32 i opened a PR but note there are some conflicts: #532

you can try resolving them, if you feel comfortable, or we (maintainers) can take care of it.
