### ISSUE TITLE
introduce r syntax highlighting

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/r-socialsci#6]
Code chunks should have the tag

`.language-r` 

as described [here](http://swcarpentry.github.io/lesson-example/04-formatting/index.html). This will make the code show up with standard R color coding and other standard aesthetics.

See also: https://github.com/datacarpentry/python-socialsci/issues/12

**Comment by ErinBecker** [comment]
- [ ] episode 00 
 - [ ] episode 01 
 - [ ] episode 02 
 - [ ] episode 03 
 - [ ] episode 04 
 - [ ] episode 05 
 - [ ] episode 06

**Comment by cengel** [comment]
Ok. So there seems to have been an issue with the episodes not being in the right folder and not being `.Rmd` format. Syntax highlighting will be added automatically once the `Rmd` files are processed by `knitr`/rmarkdown, so this issue here might become obsolete.

**Comment by fmichonneau** [comment]
@cengel this is correct. I suggest we close this issue.
