### ISSUE TITLE
Include language on tibbles in the 02-starting-with-data lesson?

### ISSUE THREAD

**Issue by potterzot** [datacarpentry/r-socialsci#71]
In the [02-starting-with-data lesson](https://github.com/datacarpentry/r-socialsci/blob/gh-pages/_episodes_rmd/02-starting-with-data.Rmd#what-are-data-frames) the language is about data frames, but the output window and examples is displayed in tibbles. This seems a little confusing. Would it be clearer to emphasize the tibble portion a little earlier?

[This is submitted as part of the instructor training closeout.]

**Comment by juanfung** [comment]
Resolved by #72 and #95
