### ISSUE TITLE
timing is wrong

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/r-socialsci#75]
See below.

**Comment by ErinBecker** [comment]
I recently taught this curriculum with @katffowler, @enfascination, @dhicks and others. We found the recommended timings to be very low. The following timings are representative of the actual time it took us to teach the lesson:

- [ ] [Episode 1](https://datacarpentry.org/r-socialsci/00-intro/index.html) - Good as is
- [ ] [Episode 2](https://datacarpentry.org/r-socialsci/01-intro-to-r/index.html) - increase teaching to 50 minutes and exercises to 30 minutes (total increase 30 minutes)
- [ ] [Episode 3](https://datacarpentry.org/r-socialsci/02-starting-with-data/index.html) - increase teaching to 50 minutes and exercises to 30 minutes (total increase 45 minutes)
- [ ] [Episode 4](https://datacarpentry.org/r-socialsci/03-dplyr-tidyr/index.html) - increase teaching to 50 minutes and exercises to 30 minutes (total increase 15 minutes)
- [ ] [Episode 5](https://datacarpentry.org/r-socialsci/04-ggplot2/index.html) - increase teaching to 80 minutes and exercises to 35 minutes (total increase 45 minutes)

Total current time of lesson: 4:15
Total recommended time of lesson (with the above increases): 6:30

We taught the workshop with the spreadsheets, OpenRefine, and R lesson and still had a few hours at the end for people to work on their own data. Increasing the recommended times for this lesson would not negatively impact the ability to teach these lessons in full in the workshop.

**Comment by ErinBecker** [comment]
@juanfung - I'm happy to put in a PR with these changes if that sounds ok to you.

**Comment by juanfung** [comment]
@ErinBecker I can take care of the PR!

**Comment by ErinBecker** [comment]
You're a lifesaver @juanfung!

**Comment by juanfung** [comment]
Resolved by #81
