### ISSUE TITLE
read_csv vs read.csv

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/r-socialsci#76]
This always leads to a long conversation because learners have heard of one or the other of these and want to talk about the differences. Think about how this can be incorporated into the curriculum as an example of reading helpfiles and understanding default options.

**Comment by atheobold** [comment]
I will look into this conversation, given the updates to `R` in version 4.0. Now that `stringsAsFactors` is `FALSE` by default, the behavior of these two functions is much less different. However, I do believe that it is still worthwhile to talk about *why* we are philosophically opposed to strings being coerced into factors.
