### ISSUE TITLE
missing part of solution in renaming factors

### ISSUE THREAD

**Issue by katffowler** [datacarpentry/r-socialsci#79]
in the solution section for the renaming factors exercise, we're missing the solution for part 1 (where you rename the factors, before plotting them in a specific order). The method is explained in the lesson (memb_assoc[is.na(memb_assoc)] <- "undetermined"), but it would be helpful to have it in the solutions to for helpers who haven't been following along with every part of the lesson.

**Comment by juanfung** [comment]
The current version of the "Starting with Data" episode has a complete solution for this exercise:
```
levels(memb_assoc) <- c("No", "Undetermined", "Yes")
```
is the only line needed. It's unnecessary to re-assign "undetermined" to the `NA` values.
