### ISSUE TITLE
action items from Curriculum Advisors

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/r-socialsci#80]
The Social Sciences CAC (social-sciences-curriculum-advisors@carpentries.org) met June 15th and 19th to discuss the full Social Sciences curriculum and provide recommendations to the Maintainers about work for these lessons between now and their next publication (December 2018). Their specific action items for this lesson are as follows: 

- Adding JSON to the R lesson
- Adding merging dataframes to the R lesson
- Adding section about ordinal data to both R and Python

Please see the [meeting minutes](https://github.com/datacarpentry/curriculum-advisors/blob/main/social-sciences/june-2018-social-sciences-minutes.md) for more details.

**Comment by maczokni** [comment]
OK so I started to work on an JSON in R lesson as per the first point here, I have a bare basics one ready. I will submit it now in a PR and then people can have a look and add to it/ give some feedback? 

I started to base it on the Python lesson (in fact the general info about JSON is all from there) but then I found the exercises hard to translate, so instead I included some examples from my usage of this. Maybe more examples, maybe some more wrangling could be useful?

**Comment by kelseygonzalez** [comment]
Thanks to @maczokni for handling the JSON section. 

Note to @atheobold and @juanfung : the dyplr & tidyr lesson still doesn't include anything on joins (which I assume is what the merging dataframes would appear as). Moreover, I don't think we have anything on ordinal data yet. Let's discuss next steps in our next maintainer meeting.

**Comment by juanfung** [comment]
Good idea!

**Comment by kelseygonzalez** [comment]
- [X] Adding JSON to the R lesson
- [ ] Adding merging dataframes to the R lesson
- [X] Adding section about ordinal data to both R and Python

**Comment by juanfung** [comment]
One minor correction: Adding section about ordinal data to *R* (python is beyond our scope). Resolved in #83

**Comment by ndporter** [comment]
CAC recommends to use `join` rather than `merge` for combining dataframes, to stay consistent with tidyverse grammar of this lesson. Given that joins are more complex and not necessary for many, this should probably be an optional episode.

And thanks again for working through the other 2 here!

**Comment by juanfung** [comment]
@ndporter thank you! will close for now then.

**Comment by ndporter** [comment]
If this is being closed, it might be good for a maintainer to make an issue related to adding a joins episode (possibly with the on hold tag) so the recommendation doesn't get lost. Thanks!
