### ISSUE TITLE
Categorical data also called nominal is SocSci

### ISSUE THREAD

**Issue by nexner** [datacarpentry/r-socialsci#83]
So many social science learners start with the nominal.ordinal/ratio system of understanding variable types. I wonder if we couldn't acknowledge this in the Factors section when we bring up categorical data? Just a quick clarifying parenthetical after the first time it mentions it, like: (also called nominal data).

**Comment by juanfung** [comment]
Personally, I feel this would be unnecessary. R does not use "nominal" for categorical data, nor am I aware of other languages that do. I think "factors" is important because the Factor class is specific to R. Most people understand what categorical data is. I don't know that a third term would help clarify things and may just lead to more confusion.

As for ordinal data, R does have ordinal factors, but this may be beyond the scope of this introductory lesson.

**Comment by shawnjanzen** [comment]
This might be a rather easy fix.  The second paragraph under the [Factors section](https://datacarpentry.org/r-socialsci/02-starting-with-data/index.html) states, 
<blockquote>Factors represent categorical data. They are stored as integers associated with labels and they can be ordered or unordered. While factors look (and often behave) like character vectors, they are actually treated as integer vectors by R. So you need to be very careful when treating them as strings.</blockquote>

We could tweak ordered or unordered to clarify them as ordinal or nominal variables.  So a changed version might look like (my additions in bold),
<blockquote>Factors represent categorical data. They are stored as integers associated with labels and they can be ordered <strong>(ordinal variable)</strong> or unordered <strong>(nominal variable)</strong>. While factors look (and often behave) like character vectors, they are actually treated as integer vectors by R. So you need to be very careful when treating them as strings.</blockquote>

Inserting this factor clarification could be done just after the instruction on re-ordering levels.  This seems like a natural placement fit.  The re-ordering code currently shows as:
`respondent_floor_type <- factor(respondent_floor_type, levels = c("earth", "cement"))
respondent_floor_type # after re-ordering`
`[1] earth  cement cement earth`
`Levels: earth cement`

Immediately after we could follow with:
<blockquote>So far, your factor is unordered, like a nominal variable.  R does not know the difference between a nominal and ordinal variable.  You make your factored an ordered factor by adding the 'ordered=T' or 'ordered=TRUE' option inside your factor function.  Note how the reported levels changed from the unordered factor above to the ordered version below.  Ordered levels use the less than sign < to denote level ranking.</blockquote>

`respondent_floor_type <- factor(respondent_floor_type, ordered=T)`
`respondent_floor_type # after setting as ordered`
`[1] earth  cement cement earth`
`Levels: earth < cement`

<blockquote>We can also see this change when we view it the variable details.</blockquote>

`glimpse(respondent_floor_type)`
`Ord.factor w/ 2 levels "earth"<"cement": 1 2 2 1`
