### ISSUE TITLE
Possible Confusion with Loading Data

### ISSUE THREAD

**Issue by KevinBWilkins** [datacarpentry/r-socialsci#84]
Hello,
In the "Starting-with-data" episode, the lesson has students load in the interview data with the following 2 commands:
library(tidyverse)
interviews <- read_csv("data/SAFI_clean.csv", na = "NULL")
The lesson then points out that the user should not see any output because this is just an assignment. However, when you run this in RStudio, you will get an output in red text about how the data was "Parsed with column specification:" and then a list of all the column IDs (see attached image). This could be confusing and mistaken as an error by new users considering the red text, and it looks like the command is outputting something (although it is not outputting the data). Perhaps we should clarify in the text of the lesson that you will see this text, but that this is not an output (and also not an error)

Kevin

![confusingoutput](https://user-images.githubusercontent.com/28013530/45231057-7ef7bd80-b290-11e8-84de-4ebace37e203.png)

**Comment by juanfung** [comment]
Good point. This is true even outside of RStudio (eg, in the R interpreter). However, the info in red is not rendered in the lesson. 

Perhaps just clarifying that the assignment creates a data frame but the user will not see the data frame (though they may see informational text about the data frame) ?
