### ISSUE TITLE
Some RStudio Wokring Directory clarity in pre-requisite episode

### ISSUE THREAD

**Issue by nsbowden** [datacarpentry/r-socialsci#9]
Here is the instance that might warrant clarification

" You can change it from the menu items for the tab, or more likely it will change when you create a project with its own folder as we will be doing later. "  I think the first it refers to the current working directory, but may not be crystal clear for new users.  Also, menu items for the tab is a little unclear.  In the Sessions menu there is a Set Working Directory option, but I am not sure if this is what is being referenced.  I think this is an important point (the whole working directory idea) for new users.

**Comment by ha0ye** [comment]
Agree - glossing over the use of RStudio projects may confuse folks, especially if they later use RGui, don't set up projects, work on a different computer, etc.

**Comment by fmichonneau** [comment]
closing in favor of #52
