### ISSUE TITLE
creating a variable with the same name as a column name

### ISSUE THREAD

**Issue by brownsarahm** [datacarpentry/r-socialsci#93]
it's a little confusing to create a variable with the same name as a column name of the dataset that we will work with. 

in the [intro to R](https://datacarpentry.org/r-socialsci/01-intro-to-r/index.html) episode it creates a `no_membrs` variabe

**Comment by juanfung** [comment]
This is a good point, especially since the vector may then remain forgotten in a user's workspace. This can create problems when referencing the column by name!
