### ISSUE TITLE
Use labs() instead of xlab(), ylab(), ggtitle()

### ISSUE THREAD

**Issue by expersso** [datacarpentry/r-socialsci#99]
## Issue

In Session 5 *Data visualisation with ggplot2*, section *Adding Labels and Titles* labels are introduced using the `xlab`, `ylab`, and `ggtitle` functions:

```r
ggplot(percent_wall_type, aes(x = village, y = percent, fill = respondent_wall_type)) +
    geom_bar(stat = "identity", position = "dodge") +
    ylab("Percent") +
    xlab("Wall Type") +
    ggtitle("Proportion of wall type by village")
```

This format is then used for a number of examples, before switching over to the `labs(x = ..., y = ..., title = ...)` format: 

```r
ggplot(percent_items, aes(x = village, y = percent)) +
    geom_bar(stat = "identity", position = "dodge") +
    facet_wrap(~ items) +
    labs(title = "Percent of respondents in each village who owned each item",
         x = "Village",
         y = "Percent of Respondents") +
    theme_bw()
```

This switch doesn't appear to be explained anywhere, which could be confusing. 

## Suggested change

Use the `labs(x = ..., y = ..., title = ...)` format consistently throughout the lesson. The `labs` function is preferable to `xlab/ylab/ggtitle`, since it generalizes to other aesthetics and labels (e.g. subtitle and caption), which don't have their own functions.

**Comment by juanfung** [comment]
Agreed! Addressed by 29a8c29
